pymilvus/client/configs.py, pymilvus/client/grpc_handler.py, pymilvus/orm/collection.py, pymilvus/orm/index.py
=> Fix index name bug

pymilvus/orm/collection.py, pymilvus/orm/index.py
=> Pop index_name even if it is empty

pymilvus/orm/collection.py
=> Pop index_name in index param

pymilvus/orm/connections.py, tests/test_connections.py
=> Fix unable to connect to secure server after add

pymilvus/client/prepare.py, tests/test_prepare.py
=> Fix prepare for properties

examples/collection.py, examples/example.py, pymilvus/orm/index.py
=> Fix bug for example

pymilvus/__init__.py, pymilvus/orm/connections.py
=> Fix unable to connect after add connection

examples/example.py, examples/example_index.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/exceptions.py, pymilvus/orm/index.py
=> Update index interface

pymilvus/orm/collection.py, pymilvus/orm/index.py
=> Don't raise exception when index is not exist

examples/example_bulkload.py, pymilvus/__init__.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/stub.py, pymilvus/orm/utility.py
=> Only allow one file for row-based import

pymilvus/orm/collection.py, pymilvus/orm/schema.py
See also: milvus-io/milvus#16536, #914
=> Make error message more clear when schema mismatch

examples/example_bulkload.py
=> Modify bulkinsert example

pymilvus/exceptions.py
=> Fix error message for primary key type

pymilvus/orm/collection.py
ref: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
=> Change doc string of Collection init and property

pymilvus/client/abstract.py
=> Fix mutation results print error

pymilvus/orm/collection.py
=> Update docs for collection

.github/workflows/check_milvus_proto.yml, .github/workflows/code_checker.yml, .github/workflows/publish_dev_package.yml, .github/workflows/pull_request.yml
=> Enable github actions on branch 2.2

README.md
=> Update Readme to the latest pymilvus version

.github/mergify.yml
=> Update mergify rules for branch 2.x

pymilvus/orm/role.py, pymilvus/orm/utility.py
=> Add the example comments for rbac methods

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, tests/test_prepare.py
See also: milvus-io/milvus#21003
=> Fix double param error

pymilvus/orm/collection.py, pymilvus/orm/partition.py
=> Use already exists schema_dict

pymilvus/client/abstract.py, pymilvus/client/grpc_handler.py
See also: milvus-io/milvus#20870
=> Remove round when parsing query result

pymilvus/client/types.py
=> [cherry-pick] Get bulkinsert progress percent value

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/decorators.py
See also: milvus-io/milvus#21618
=> Fix not checking replica_number in load

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
=> Fix not check replica_number when load_partitions

pymilvus/client/grpc_handler.py
=> Change default connection timeout to 10s

pymilvus/orm/utility.py
=> remove deprecated code

examples/resource_group.py, pymilvus/client/types.py
=> fix resource group info def

examples/resource_group.py, pymilvus/client/types.py
=> fix resource group def

examples/resource_group.py, pymilvus/client/grpc_handler.py, pymilvus/orm/default_config.py
=> fix describe/list rg err msg

CHANGELOGS.md, pymilvus/v2/__init__.py, pymilvus/v2/apis.py, pymilvus/v2/async_apis.py, pymilvus/v2/grpc_handler.py, pymilvus/v2/types.py
=> Add framework of pymilvus.v2

pymilvus/client/check.py, pymilvus/client/prepare.py
=> add param check

pymilvus/orm/collection.py, pymilvus/orm/connections.py, pymilvus/orm/index.py, pymilvus/orm/partition.py, pymilvus/orm/role.py, pymilvus/orm/utility.py
=> Remove deprecation on orm

pymilvus/client/grpc_handler.py, pymilvus/client/types.py, tests/test_types.py
=> expose rg info in replica

docs/source/api/collection.rst, docs/source/api/partition.rst, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/exceptions.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py
Signed-off-by: lixinguo <xinguo.li@zilliz.com>
=> Support upsert

pymilvus/client/types.py
fix https://github.com/milvus-io/milvus/issues/22220
=> expose rg info

pymilvus/orm/utility.py
=> refine rg api

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/utils.py
Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
https://github.com/milvus-io/milvus/issues/22342
=> Fix some error

examples/resource_group.py, pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/types.py, pymilvus/orm/utility.py, tests/test_types.py
sync rg changes
fix describe/list rg err msg (#1291)
fix load collection (#1293)
add param check (#1297)
expose rg info in replica (#1305)
refine rg api (#1310)
expose rg info (#1307)
=> sync rg changes

pymilvus/client/entity_helper.py
Otherwise it's impossible to insert string with len same as varchar max len.
=> fix check string max len (#1304)

pymilvus/aio/apis.py, pymilvus/v2/apis.py, tests/conftest.py, tests/test_v2_apis.py
- drop_alias, alter_alias, create_alias
- drop_collection, has_collection, list_collections, release_collection
- create_partition, has_partition, drop_partition, release_partitions
- drop_index, list_indexes
=> Add some APIs

pymilvus/client/utils.py
issue: https://github.com/milvus-io/milvus/issues/22623
=> Fix collection schema mismatch entities

pymilvus/client/prepare.py
issue: https://github.com/milvus-io/milvus/issues/22623
/kind bug
=> Fix collection schema mismatch entities (#1325)

pymilvus/orm/schema.py, tests/test_schema.py
=> Fix error message when insert mismatch datatypes

pymilvus/orm/schema.py, tests/test_schema.py
- Fix possible KeyError if description is not set (#1328)
- Fix error message when insert mismatch datatypes (#1333)
See also: #1324
=> Multi cherry picks from master branch

pymilvus/client/grpc_handler.py
related: https://github.com/milvus-io/milvus/issues/22921
=> Fix FlushAll timeout [pick#1340]

pymilvus/client/grpc_handler.py
related: https://github.com/milvus-io/milvus/issues/22921
=> Fix FlushAll timeout

.github/workflows/publish_dev_package.yml
=> Fix publish dev packge to testpypi action

pymilvus/client/types.py, tests/test_types.py
See also: milvus-io/milvus#23396
=> Fix print too many nodeIDs of Replica

pymilvus/client/abstract.py, pymilvus/orm/search.py
=> Print all output fields

pymilvus/client/grpc_handler.py, pymilvus/client/stub.py, pymilvus/client/utils.py, pymilvus/orm/utility.py, tests/test_utils.py
=> Add an utility to get server type (#1381)

pymilvus/orm/utility.py
=> List indexes by field name (#1386)

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/stub.py, pymilvus/orm/collection.py, pymilvus/settings.py
=> Remove default of shards_num for new collection

pymilvus/settings.py
see also: milvus-io/milvus#23627
=> Fix typo in config

pymilvus/client/prepare.py
Float and binary vector error message shared which results in incorrect message
=> Fix incorrect dim error msg

pymilvus/client/grpc_handler.py, pymilvus/client/utils.py, tests/test_utils.py
=> Fix get_server_type

pymilvus/client/grpc_handler.py, pymilvus/client/utils.py, tests/test_utils.py
=> Fix get_server_type (#1397)

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py
See also: milvus-io/milvus#23372
=> Add param check for shards_num

pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py
=> Sync partiton APIs with collection

pymilvus/client/prepare.py, pymilvus/milvus_client/defaults.py, pymilvus/milvus_client/milvus_client.py, pymilvus/milvus_client/milvus_client_tests.py, requirements.txt
- Fix incorrect dim error msg (#1394)
- Include MilvusClient (#1374)
=> Multi cherry picks from master

pymilvus/client/abstract.py, pymilvus/orm/collection.py
See also: milvus-io/milvus#23853
=> Add num_shards property in Collection

pymilvus/client/grpc_handler.py
=> Remove unnecessary index check

pymilvus/grpc_gen/schema_pb2.py, pymilvus/grpc_gen/schema_pb2.pyi
/kind feature
related https://github.com/milvus-io/milvus/issues/23389
=> [Cherry-Pick] Update proto to support JSON type

pymilvus/client/utils.py
/kind bug
related https://github.com/milvus-io/milvus/issues/24144 https://github.com/milvus-io/milvus/issues/24132
=> Fix failed to calculate the length of JSON data

pymilvus/client/grpc_handler.py
/kind bug
related https://github.com/milvus-io/milvus/issues/24164
=> Fix convert all JSON data to results for each entity

pymilvus/client/prepare.py
issue: https://github.com/milvus-io/milvus/issues/24140
=> Fix num_partitions type

examples/iterator.py, pymilvus/client/constants.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/constants.py, pymilvus/orm/iterator.py
support query and search Milvus collection by page and page, and also, speeding query pagination by idk-side cache
=> support iterator for query and search

pymilvus/client/abstract.py, pymilvus/client/prepare.py, pymilvus/exceptions.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py
Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
https://github.com/milvus-io/milvus/issues/23337
=> Support Default Value

pymilvus/client/abstract.py, pymilvus/client/grpc_handler.py, pymilvus/client/utils.py
- Fix lost JSON result (https://github.com/milvus-io/pymilvus/pull/1432)
- Fix failed to calculate the length of JSON data (https://github.com/milvus-io/pymilvus/pull/1433)
- Fix convert all JSON data to results for each entity (https://github.com/milvus-io/pymilvus/pull/1435)
/kind bug
related https://github.com/milvus-io/milvus/issues/23389
=> [Cherry-Pick] Fix JSON related bugs

pymilvus/milvus_client/milvus_client.py
Add a distance metric selection to MilvusClient
=> adding distance metric selection

pymilvus/orm/schema.py
https://github.com/milvus-io/pymilvus/issues/1450
=> Fix default value appear when not set

pymilvus/__init__.py, pymilvus/client/prepare.py, pymilvus/client/stub.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/collection.py, pymilvus/orm/connections.py, tests/test_prepare.py
- Unify num_shards and mark shards_num as deprecated (#1412)
- adding distance metric selection (#1428)
- Fix None user/password (#1443)
- deduce secure from user/pass (#1445)
- last few fixes (#1408)
See also: milvus-io/milvus#23853
=> Multi cherry-picks from master branch

examples/database.py, examples/role_and_privilege.py, pymilvus/__init__.py, pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/types.py, pymilvus/orm/connections.py, pymilvus/orm/db.py, pymilvus/orm/role.py, tests/test_connections.py
- RBAC supports Database validation (#1396)
- Support database API (#1401)
- Using database by URI (#1420)
=> Multi cherry from 2.2 to master

pymilvus/client/prepare.py, tests/test_prepare.py
/kind bug
issue: https://github.com/milvus-io/milvus/issues/24471
=> Fix bug for insert rows when enable auto_id

pymilvus/orm/schema.py
- change repr of schema to one line
- remove set auto_id from collection schema
See also: #1182
=> Set auto_id default value False

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
issue: https://github.com/milvus-io/milvus/issues/24506
=> Backward compatibility logic for Connect

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
issue: https://github.com/milvus-io/milvus/issues/24506
=> Backward compatibility logic for Connect (#1481)

pymilvus/client/grpc_handler.py
issue: https://github.com/milvus-io/milvus/issues/24372
=> Call Connect after db name changed

pymilvus/client/grpc_handler.py
issue: https://github.com/milvus-io/milvus/issues/24372
=> Call Connect after db name changed (#1484)

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
issue: https://github.com/milvus-io/milvus/issues/24444, https://github.com/milvus-io/milvus/issues/24506
=> Remind users when unimplemented feature was called

examples/binary_example.py, pymilvus/client/entity_helper.py
=> Fix bug: failed to insert binary vector

examples/binary_example.py, pymilvus/client/entity_helper.py
=> Fix bug for insert binary vectors by rows

pymilvus/client/prepare.py
issue: https://github.com/milvus-io/milvus/issues/24531
=> Pass the is_dynamic field to the milvus server

pymilvus/orm/connections.py
issue: https://github.com/milvus-io/milvus/issues/24372
=> Fix check DB available failed

pymilvus/orm/connections.py
issue: https://github.com/milvus-io/milvus/issues/24372
=> Fix check DB available failedFix bug: failed to check invalid db due to broken parameter ordering

pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/24551
=> Fix insert hangs when insert more fields than schema defined

pymilvus/client/prepare.py
https://github.com/milvus-io/milvus/issues/23849
=> Do not set metric_type default value in search params

pymilvus/client/check.py, pymilvus/client/grpc_handler.py
issue: https://github.com/milvus-io/milvus/issues/23905
=> Check if db name is invalid type

pymilvus/client/check.py, pymilvus/client/grpc_handler.py
issue: https://github.com/milvus-io/milvus/issues/23905
=> Check if db name is invalid type (#1507)

pymilvus/client/check.py, tests/test_check.py
=> Remove useless check function

pymilvus/client/check.py, tests/test_check.py
=> Remove useless check function (#1510)

pymilvus/client/prepare.py
https://github.com/milvus-io/milvus/issues/23849, https://github.com/milvus-io/milvus/issues/24575
=> Do not set metric_type default value in search params (#1469)

pymilvus/client/grpc_handler.py
=> Pick query impl from master

pymilvus/client/abstract.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/collection.py
=> Fix bugs: describe_collection return dict and query filter parameter

pymilvus/client/abstract.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/collection.py
=> Fix bugs: describe_collection and query filter parameter

pymilvus/orm/schema.py
relate https://github.com/milvus-io/milvus/issues/24754
https://github.com/milvus-io/milvus/issues/24578
=> Fix bug: should check invalid primary field

pymilvus/orm/schema.py
relate https://github.com/milvus-io/milvus/issues/24754
https://github.com/milvus-io/milvus/issues/24578
=> Fix bug: should check invalid primary field (#1528)

pymilvus/milvus_client/milvus_client.py, pymilvus/orm/schema.py
=> Defer check_fields when use milvus_client

pymilvus/client/grpc_handler.py
/kind feature
related https://github.com/milvus-io/milvus/issues/23094
=> Support async refresh

pymilvus/milvus_client/milvus_client.py, pymilvus/orm/schema.py
=> Defer check_fields when use milvus_client (#1536)

pymilvus/orm/constants.py, pymilvus/orm/iterator.py
=> fix iterator params accepted is not consistent and cursor updation problem

pymilvus/client/entity_helper.py
/kind feature
related https://github.com/milvus-io/milvus/issues/24930
=> Support Chinese in JSON

pymilvus/client/entity_helper.py
/kind feature
related https://github.com/milvus-io/milvus/issues/24930
=> Support Chinese in JSON (#1541)

examples/non_ascii_encode.py, pymilvus/orm/connections.py
=> Refinement: print clearer indication of the valid URI

pymilvus/orm/partition.py
=> Create partition with just collection name

pymilvus/orm/iterator.py
issues:  https://github.com/milvus-io/milvus/issues/25003
=> Fix range_filter and radius in param but don't set

pymilvus/orm/constants.py, pymilvus/orm/iterator.py
iteration support COSINE, Jaccurd and Hamming
=> correct radius judgement

pymilvus/exceptions.py, pymilvus/milvus_client/milvus_client.py
issue #1554 
releated https://github.com/milvus-io/milvus/issues/25110
=> Enable user to set max_length for pk field of string type

pymilvus/client/grpc_handler.py, pymilvus/decorators.py, tests/test_decorators.py, tests/test_grpc_handler.py
=> Retry RPCError except for DEADLINE_EXCEEDED and UNIMPLEMENTED

pymilvus/client/grpc_handler.py, pymilvus/decorators.py, tests/test_decorators.py, tests/test_grpc_handler.py
=> Retry RPCError except for DEADLINE_EXCEEDED

pymilvus/client/grpc_handler.py, pymilvus/client/stub.py, pymilvus/orm/utility.py
Reverts milvus-io/pymilvus#1571
=> Revert "Create index brefore wait for completion"

pymilvus/client/grpc_handler.py, pymilvus/client/stub.py, pymilvus/orm/utility.py
Reverts milvus-io/pymilvus#1576
=> Revert "Create index brefore wait for completion (#1571)"

pymilvus/client/abstract.py, pymilvus/client/prepare.py
=> Fix describe_collection failed when max_length set to non-varchar field

pymilvus/client/abstract.py, pymilvus/client/prepare.py
=> Fix describe_collection failed when max_length set to non-varchar field (#1584)

pymilvus/exceptions.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/schema.py
behavior changed https://github.com/milvus-io/milvus/pull/24907
=> add autoID to varchar dataType

pymilvus/decorators.py
=> Add fast fail error code

pymilvus/client/entity_helper.py
See also: milvus-io/milvus#25413, milvus-io/milvus#23403
=> Fix auto_id=False insertion serror

pymilvus/client/abstract.py
See also: milvus-io/milvus#23661
=> Fix search ouput field BianryVector error

pymilvus/orm/collection.py
See also: milvus-io/milvus#25573
=> Fix SearchIterator init error

pymilvus/decorators.py
=> Increase the number of retry times and decrease the duration of sleep

pymilvus/decorators.py
=> Increase the number of retry times and decrease the duration of sleep (#1598)

pymilvus/client/abstract.py
See also: milvus-io/milvus#23661
=> Fix search ouput field BianryVector error (#1591)

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
See also: milvus-io/milvus#25695
=> Donot retry on RESOURCE_EXHAUSTED

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/utility.py
See also: milvus-io/milvus#25872
=> Fix rename collection raise cannot be None error

pymilvus/client/types.py
Fix this bug: https://github.com/milvus-io/milvus/issues/25168
=> Fix a bug of bulkinsert

pymilvus/client/prepare.py, tests/test_prepare.py
Fixes #1617
ps: need to cherry-pick to master.
=> AlterCollection use KeyValuePair.

pymilvus/client/prepare.py, tests/test_prepare.py
cherry-pick from #1618 
Fixes #1617
=> AlterCollection use KeyValuePair. (#1618)

pymilvus/client/grpc_handler.py
=> Fix exception message (#1632)

pymilvus/client/prepare.py
=> Fixbug: should fill empty dict when using dyanmic field

pymilvus/client/prepare.py
=> Fixbug: should fill empty dict when using dynamic field

pymilvus/client/check.py
=> Remove unused index and metric_type check

pymilvus/client/grpc_handler.py, pymilvus/client/utils.py, pymilvus/orm/iterator.py, pymilvus/orm/schema.py, pyproject.toml
related: https://github.com/milvus-io/milvus/issues/26355
=> deep copy params to avoid reuse parameters(#26355)

pymilvus/orm/utility.py
added missing `using` parameter to docstring
=> complete docstring for `list_collections()`

pymilvus/milvus_client/milvus_client.py
https://github.com/milvus-io/pymilvus/pull/1631
The previous PR was unsigned and it was a bit of a hassle to re-sign it, so I just re-submitted the PR
=> Disable logger from polluting other modules

pymilvus/client/abstract.py, pymilvus/client/prepare.py, pymilvus/exceptions.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, pymilvus/orm/schema.py
- Revert "Support Default Value (#1444)" This reverts commit 5a581ce6097f36b20687f5aeb988db82ac6212e9.
- Revert "Fix default value appear when not set (#1451)" This reverts commit 69d9b409dd8ee3a0d1227145efc38015c97a4607.
- Revert "Fix default value store in unknow dataType (#1462)" This reverts commit cf81b472d7b0307d644f49b4772f64b58c1bf974.
- Revert "Make default value set None valid (#1473)" This reverts commit 72bec7c94446761ab4de4e57d1952b21d59cbfe6.
=> Revert support default value

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py
/kind bug
issue: https://github.com/milvus-io/milvus/issues/26820
=> Pass segment ids when get flush state

pymilvus/orm/connections.py
/kind bug
[milvus #26833](https://github.com/milvus-io/milvus/issues/26833)
=> while parse uri, overwrite the db_name with default

pyproject.toml, requirements.txt
=> Update grpcio version range

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/utility.py
https://github.com/milvus-io/milvus/issues/26777
=> Add db parameter in flush_all

pymilvus/client/grpc_handler.py
=> Fix pass extra param

pymilvus/client/abstract.py, pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/client/types.py, pymilvus/client/utils.py, pymilvus/orm/constants.py, pymilvus/orm/schema.py
milvus pr: https://github.com/milvus-io/milvus/pull/26369
=> Support new DataType: Array

pymilvus/client/asynch.py, pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/decorators.py, pymilvus/exceptions.py, pymilvus/orm/mutation.py, tests/test_create_collection.py, tests/test_decorators.py, tests/test_grpc_handler.py
issue: https://github.com/milvus-io/milvus/issues/26275
=> Change error_code to code

examples/example_bulkwriter.py, pymilvus/bulk_writer/bulk_writer.py
https://github.com/milvus-io/pymilvus/issues/1710
=> [cherry-pick] Support numpy type value for bulkwriter

pymilvus/client/grpc_handler.py, pymilvus/exceptions.py
See also: milvus-io/milvus#27624
=> Fix INDEX_NOT_EXIST error code

pymilvus/client/grpc_handler.py
/kind bug
https://github.com/milvus-io/milvus/issues/27385
=> Fix rename_collection will move collection to default db

pymilvus/client/abstract.py
/kind bug
https://github.com/milvus-io/milvus/issues/27055
=> Fix describe miss some params

pyproject.toml
=> Add a lower bound for minio

pymilvus/orm/role.py
=> Improve the default db for the rbac

pymilvus/client/abstract.py
This reverts commit f52eefa1d09759603057208f3020c85310f4134b.
=> Revert "Fix describe miss some params (#1742)"

pymilvus/orm/connections.py
issue: https://github.com/milvus-io/pymilvus/issues/1756
=> Fix api key

pymilvus/decorators.py
=> Change unimpleted log level to debug

pymilvus/client/abstract.py
=> Convert the result to python basic types to enable json dumps

pymilvus/exceptions.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, pymilvus/orm/utility.py
let server check whether partition existed,
then we can get better error details.
=> enhance: remove partition existance check

pymilvus/orm/iterator.py
=> adjust metrics comparison

pymilvus/client/asynch.py, pymilvus/client/grpc_handler.py, pymilvus/client/utils.py
This PR checks status.error_code for compactibility with Milvus 2.2.x.
issue: https://github.com/milvus-io/pymilvus/issues/1804
=> fix: Fix compactibility of exception with Milvus 2.2.x

pymilvus/client/constants.py, pymilvus/client/prepare.py, pymilvus/orm/iterator.py
=> support search group-by(#1809)

pymilvus/orm/iterator.py
=> add limit for too large ef to avoid huge latency for iterator(#1814)

pymilvus/orm/iterator.py
related: https://github.com/milvus-io/milvus/issues/28821
=> fix exceeding width of search_iterator(#1823)

pymilvus/orm/iterator.py
=> cp: Fix 1823-2.3

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py
relate: https://github.com/milvus-io/pymilvus/issues/1828
=> Support delete with consistency level

pymilvus/client/grpc_handler.py, pymilvus/orm/connections.py
=> Auto reconnection when channel state changed to idle

pymilvus/orm/connections.py, tests/test_connections.py
=> fix: Fix bug for add connection when url is https

examples/example_group_by.py, pymilvus/client/prepare.py
=> enchance: refine group_by_field and provide group_by example(#1809)

examples/bfloat16_example.py, examples/float16_example.py, pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/orm/schema.py, test_requirements.txt, tests/test_abstract.py, tests/test_collection.py, tests/test_create_collection.py, tests/test_schema.py, tests/test_types.py
After pr [#28427](https://github.com/milvus-io/milvus/pull/28427)
=> Add float16 and bfloat16 approve

pymilvus/client/entity_helper.py, pymilvus/exceptions.py
issue: https://github.com/milvus-io/milvus/issues/30394
=> Fix bug for insert ndarray in json field

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/check.py, pymilvus/milvus_client/index.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/schema.py
issues: https://github.com/milvus-io/pymilvus/issues/1864 https://github.com/milvus-io/pymilvus/issues/1866 https://github.com/milvus-io/pymilvus/issues/1869 https://github.com/milvus-io/pymilvus/issues/1870 https://github.com/milvus-io/pymilvus/issues/1871 https://github.com/milvus-io/pymilvus/issues/1872 https://github.com/milvus-io/pymilvus/issues/1879 https://github.com/milvus-io/pymilvus/issues/1880 https://github.com/milvus-io/pymilvus/issues/1883 https://github.com/milvus-io/pymilvus/issues/1884 https://github.com/milvus-io/pymilvus/issues/1885 https://github.com/milvus-io/pymilvus/issues/1886 https://github.com/milvus-io/pymilvus/issues/1894 https://github.com/milvus-io/pymilvus/issues/1895 https://github.com/milvus-io/pymilvus/issues/1896
=> Fix several bugs related to MilvusClient

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/ts_utils.py, pymilvus/orm/collection.py, pymilvus/orm/iterator.py, pymilvus/orm/schema.py, pyproject.toml, requirements.txt, test_requirements.txt
=> enhance: [cherry-pick]upgrade ruff and coding styles

pymilvus/client/utils.py
issue: https://github.com/milvus-io/milvus/issues/30437
=> fix:the length of fields data is not consistence when fp16/bf16 vectors as query output fields

examples/milvus_client/alias.py, pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py
issue : https://github.com/milvus-io/pymilvus/issues/1891 https://github.com/milvus-io/pymilvus/issues/1892
=> Add list_aliases and describe_alias

pymilvus/client/abstract.py, pymilvus/client/entity_helper.py, pymilvus/client/utils.py, pymilvus/orm/schema.py, tests/test_abstract.py, tests/test_collection.py
1. fix: fp16/bf16 vector can't get origin vector as output fields;
2. add some size check of fp16/bf16 vectors.
=> fix: can't get vector when fp16/bf16 vectors as output fields

.github/workflows/check_milvus_proto.yml, .github/workflows/code_checker.yml, .github/workflows/nightly_ci.yml, .github/workflows/publish_dev_package.yml, .github/workflows/publish_on_release.yml, .github/workflows/pull_request.yml
Make all the GitHub actions up 2 date
=> ci: Update actions

pymilvus/client/grpc_handler.py, pymilvus/orm/collection.py
return value of conn.insert_rows and conn.batch_insert is already MutationResult/MutationFuture.
=> collection.insert to return connection insert result directly

pymilvus/client/grpc_handler.py, pymilvus/orm/collection.py
Reverts milvus-io/pymilvus#1943
=> Revert "collection.insert to return connection insert result directly"

pymilvus/milvus_client/milvus_client.py, pymilvus/orm/schema.py
issue https://github.com/milvus-io/pymilvus/issues/1933
=> Fix several bugs reated to MilvusClient

pymilvus/decorators.py, tests/test_decorators.py
=> fix: Donot retry on UnImplemented

pymilvus/client/abstract.py, pymilvus/orm/schema.py
issue https://github.com/milvus-io/pymilvus/issues/1522
=> Fix bug: add enable_dynamic_field in result of DescribeCollection

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/orm/connections.py
=> enhance: [cherry-pick]change connection timeout to clearer msg

examples/milvus_client/customize_schema_auto_id.py, examples/milvus_client/non_ascii_encode.py, examples/milvus_client/rbac.py, pymilvus/bulk_writer/buffer.py, pymilvus/milvus_client/index.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/schema.py
=> Avoiding parameter conflicts and add compatibility logic

examples/hello_milvus_simple.py, examples/hello_milvus_simple2.py, examples/milvus_client/alias.py, examples/milvus_client/customize_schema.py, examples/milvus_client/customize_schema_auto_id.py, examples/milvus_client/index.py, examples/milvus_client/non_ascii_encode.py, examples/milvus_client/partition.py, examples/milvus_client/rbac.py, examples/milvus_client/simple.py, examples/milvus_client/simple_auto_id.py, pymilvus/client/abstract.py, pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/types.py, pymilvus/exceptions.py, pymilvus/milvus_client/check.py, pymilvus/milvus_client/index.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/schema.py
Pick the newly created MilvusClient interface from the master branch.
=> pick MilvusClient from master

pymilvus/orm/utility.py
https://github.com/milvus-io/milvus/issues/30743
=> fix: rename_collection not apply in current db

pymilvus/client/abstract.py, pymilvus/client/prepare.py, pymilvus/exceptions.py, pymilvus/orm/schema.py
=> Support clustering key in create collection

examples/hello_model.py, pymilvus/model/__init__.py, pymilvus/model/base.py, pymilvus/model/dense/__init__.py, pymilvus/model/dense/openai.py, pymilvus/model/dense/sentence_transformer.py, pymilvus/model/hybrid/__init__.py, pymilvus/model/hybrid/bge_m3.py, pymilvus/model/sparse/__init__.py, pymilvus/model/sparse/bm25/__init__.py, pymilvus/model/sparse/bm25/bm25.py, pymilvus/model/sparse/bm25/lang.yaml, pymilvus/model/sparse/bm25/tokenizers.py, pymilvus/model/sparse/splade.py, pyproject.toml
Add follwow embedding models
- bm25(sparse)
- splade(sparse)
- sentence transformers(dense)
- openai(dense)
- bge-m3(hybrid)
=> Add embedding models to pymilvus.

pymilvus/model/hybrid/bge_m3.py, pymilvus/model/sparse/bm25/bm25.py, pymilvus/model/sparse/splade.py
- change splade's output from List[csr_array] to csr_array.
- change bge m3's  sparse output from List[csr_array] to csr_array.
- change bm25's output from List[csr_array] to csr_array.
- add batch_size feature of splade.
- add batch_size feature of bge m3.
- remove multiprocessing of bm25's encode_documents and encode_queries.
=> Change the sparse embedding from List[csr_array] to csr_array

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
=> enhance: retry on inconsistent requery

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
=> enhance: retry on inconsistent requery (#1975)

README.md
=> fix: Update versions in readme to latest

README.md
=> fix: [cherry-pick]Update versions in readme to latest

pymilvus/client/grpc_handler.py
=> fix: [cherry-pick]Remove the dependency of server_name to others

pymilvus/client/grpc_handler.py
=> fix: Remove the dependency of server_name to others

examples/hello_hybrid_sparse_dense.py
Signed-off-by: Author Name <jiang.chen@zilliz.com>
=> Add friendly setup instructions to hello_hybrid_sparse_dense.py

examples/bfloat16_example.py, examples/float16_example.py, pymilvus/client/blob.py, pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/orm/prepare.py
=> fix: Use wrong placeholder type for bf16 and float16

examples/bfloat16_example.py, examples/float16_example.py, pymilvus/client/blob.py, pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/orm/prepare.py
=> fix: [cherry-pick]Use wrong placeholder type for bf16 and float16

pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/orm/collection.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py, pyproject.toml
See also: #2018, #2004, #2016
---------
=> fix: [cherry-pick]restrict input/search type for vector fields (#2025)

examples/hello_hybrid_sparse_dense.py
pr: https://github.com/milvus-io/milvus/pull/31062
=> enhance: [2.4] Update hello_hybrid_sparse_dense.py example to include BGE reranker

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
Reverts milvus-io/pymilvus#1975
=> Revert "enhance: retry on inconsistent requery"

pymilvus/client/prepare.py
issue https://github.com/milvus-io/pymilvus/issues/2050
=> fix: pass offset parameter for hybrid search to server

examples/hello_cost.py, examples/milvus_client/simple_cost.py, pymilvus/client/abstract.py, pymilvus/client/asynch.py, pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/mutation.py
issue: https://github.com/milvus-io/milvus/issues/30436
=> support the report value in the dml and dql request

pymilvus/client/entity_helper.py
=> [2.4] change sparse related errors to ParamError

examples/hello_sparse.py, pymilvus/client/abstract.py, pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/orm/collection.py, pymilvus/orm/iterator.py, pymilvus/orm/partition.py, pymilvus/orm/prepare.py, pyproject.toml, requirements.txt
=> remove scipy dependency for sparse while still supporting scipy sparse matrix

examples/example_bulkwriter.py, pymilvus/__init__.py, pymilvus/bulk_writer/__init__.py, pyproject.toml
=> enhance: Make bulk_writer's requirments optional

pymilvus/client/types.py
issue: https://github.com/milvus-io/milvus/issues/30436
link pr: #2092
=> [2.4] fix the str function of the extra list

pymilvus/client/types.py
issue: https://github.com/milvus-io/milvus/issues/30436
link pr: https://github.com/milvus-io/pymilvus/pull/2055
=> fix the str function of the extra list

pymilvus/orm/collection.py
issue: https://github.com/milvus-io/milvus/issues/29419 
as range search supported has been added to sparse index
=> feat: allowing search iterator on sparse float vector field

pymilvus/orm/collection.py
=> feat: [2.4] allowing search iterator on sparse float vector field

pymilvus/client/entity_helper.py
=> [2.4] Accept list of single row scipy.sparse object as input for insert/search

pymilvus/orm/index.py
https://github.com/milvus-io/milvus/issues/33327
=> fix: use the existed index_name

pymilvus/orm/index.py
https://github.com/milvus-io/milvus/issues/33327
=> fix: use the existed index_name (#2107)

pymilvus/client/abstract.py
=> enhance: print search result more elegantly (#2123)

pymilvus/client/abstract.py
=> enhance: print search result more elegantly

pymilvus/settings.py
=> change the load status check interval to 0.2s

pymilvus/settings.py
=> [2.4] change the load status check interval to 0.2s

.github/workflows/check_milvus_proto.yml, .github/workflows/code_checker.yml, .github/workflows/pull_request.yml, Makefile, tests/test_milvus_lite.py
=> enhance: Check PyMilvus on Windows platform

pymilvus/orm/collection.py, pymilvus/orm/partition.py
=> enhance: Remove the logic to set replica_number=1 by default (#2163)

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/exceptions.py, pymilvus/orm/collection.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/29258
=> enhance: upsert support autoid

pymilvus/orm/iterator.py
=> enhance:expose reduce_stop_for_best to users(#2181)

pymilvus/client/grpc_handler.py, pymilvus/orm/collection.py
=> [cherry-pick] Don't export rows info in index params

pymilvus/exceptions.py, pymilvus/orm/schema.py, tests/test_create_collection.py
=> fix: [cherry-pick] remove limitation clustering key can not be primary key

examples/milvus_client/simple_cost.py, pymilvus/client/abstract.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
=> enhance: hide zero values ​​when printing

pymilvus/client/entity_helper.py
=> fix: [2.4]unclear error msg for varchar field

pymilvus/client/entity_helper.py
=> fix: unclear error msg for varchar field

pymilvus/orm/schema.py
=> fix: select a single column consisting of a list of column names

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/exceptions.py, pymilvus/orm/collection.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/29258
=> enhance: upsert support autoid (#2173)

pymilvus/client/prepare.py
=> Bulkinsert supports importing binlog

pymilvus/client/constants.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, tests/test_prepare.py
issue: https://github.com/milvus-io/milvus/issues/35464
=> feat: [2.4] add page_retain_order param during search with offset

pymilvus/client/constants.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, tests/test_prepare.py
issue: https://github.com/milvus-io/milvus/issues/35464
=> feat: add page_retain_order param during search with offset

pymilvus/bulk_writer/buffer.py, pymilvus/client/abstract.py, pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/orm/iterator.py, pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/31728
=> enhance: support null and default value

pymilvus/client/abstract.py, pymilvus/client/prepare.py, pymilvus/orm/schema.py
- issue: https://github.com/milvus-io/milvus/issues/35273
=> feat: support the mmap_enable param in the field schema

pymilvus/bulk_writer/buffer.py, pymilvus/client/abstract.py, pymilvus/client/prepare.py, pymilvus/orm/iterator.py, pymilvus/orm/schema.py
- issue: https://github.com/milvus-io/milvus/issues/35273
- pr: #2238
=> feat: [2.4] support the mmap_enable param in the field schema

pyproject.toml
=> enhance: [cp24] loose grpcio upper limit

pyproject.toml
=> enhance: loose the upper limit for grpcio

pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, tests/test_prepare.py
issue: https://github.com/milvus-io/milvus/issues/35464
=> fix: move page_retain_order to the same level as radius

pymilvus/client/constants.py, pymilvus/client/prepare.py
=> add strict_group_size and rank_group_scorer for hybrid_search(#2253)

pymilvus/exceptions.py, pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/35944
=> fix: not report error when setting default_value=None

examples/example_bulkinsert_csv.py, pymilvus/bulk_writer/buffer.py, pymilvus/bulk_writer/bulk_writer.py, pymilvus/bulk_writer/constants.py, pymilvus/bulk_writer/local_bulk_writer.py, pymilvus/bulk_writer/remote_bulk_writer.py, pymilvus/client/prepare.py
Milvus has supported csv format in bulkinsert, this pr synchronizes this support to pymilvus.
See this pr in milvus for detail information https://github.com/milvus-io/milvus/pull/34938
=> enhance: Bulkinsert support csv

pymilvus/client/abstract.py
https://github.com/milvus-io/milvus/issues/36457
=> fix: not put 'default_value' in dict

pymilvus/client/abstract.py, pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/exceptions.py, tests/test_prepare.py
https://github.com/milvus-io/milvus/issues/36354
https://github.com/milvus-io/milvus/issues/36486
=> fix not check None Type in json and support no need to pass in None when insert row

pymilvus/orm/iterator.py
=> fix: reset offset to zero after seek(#2292)

pymilvus/client/prepare.py
See also: milvus-io/milvus#36983
=> fix: Passing messages to code in ParamError

pymilvus/client/prepare.py
See also: milvus-io/milvus#36983
=> fix: Passing messages to code in ParamError (#2304)

examples/iterator.py, pymilvus/orm/iterator.py
=> enhance: handling cp file for query iterator(#2306)

pymilvus/orm/iterator.py
=> enhance: handling abormal iterator cp file(#2306)

pymilvus/bulk_writer/buffer.py, pymilvus/bulk_writer/bulk_writer.py
https://github.com/milvus-io/milvus/issues/37196
=> fix: bulkwriter to skip function output fields

examples/milvus_client/compact.py, examples/milvus_client/flush.py, examples/milvus_client/get_server_version.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
issue: https://github.com/milvus-io/pymilvus/issues/2325
=> feat: Add compact, get_server_version and flush api

pymilvus/milvus_client/milvus_client.py
related: [#2332](https://github.com/milvus-io/pymilvus/issues/2332)
=> Update return type of describe_role to Dict (#2332)

pymilvus/milvus_client/milvus_client.py
=> [2.4]Use filter_params for milvus client

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/role.py
issue: https://github.com/milvus-io/pymilvus/issues/2353
=> fix: [2.4] add privilege group orm

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/role.py
issue: https://github.com/milvus-io/pymilvus/issues/2353
=> fix: add privilege group orm

pyproject.toml
=> fix: Add upper limit for grpcio to 1.67.1

pymilvus/orm/role.py
=> fix: RBAC fix privilege group orm

pymilvus/orm/role.py
cherry-pick from master: https://github.com/milvus-io/pymilvus/pull/2366
=> fix: [2.4] RBAC fix privilege group orm

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, tests/test_prepare.py
Also optinal variables default value should always be None. And empty str is always invalid variable
See also: #2327
pr: #2350
=> fix: cannot pass consistency level for delete

examples/orm/bitmap_index_example.py, examples/test_bitmap_index.py
=> enhance: add bitmap index example

pymilvus/decorators.py
=> enhance: Enhance log messages when Connect with server failed

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/role.py
=> enhance: grant/revoke v2 optional db and collection params

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/role.py
=> enhance: [2.4] grant/revoke v2 optional db and collection params

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/role.py
cherry-pick from master: https://github.com/milvus-io/pymilvus/pull/2386
=> enhance: [2.5] grant/revoke v2 optional db and collection params

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/role.py, pymilvus/orm/utility.py
cherry-pick from master: https://github.com/milvus-io/pymilvus/pull/2399, https://github.com/milvus-io/pymilvus/pull/2403
issue: https://github.com/milvus-io/milvus/issues/37031, https://github.com/milvus-io/milvus/issues/38052
=> fix: [2.4] fix list aliases rpc call and grant/revoke v2

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/role.py, pymilvus/orm/utility.py
cherry-pick from master: https://github.com/milvus-io/pymilvus/pull/2399, https://github.com/milvus-io/pymilvus/pull/2403
issue: https://github.com/milvus-io/milvus/issues/37031, https://github.com/milvus-io/milvus/issues/38052
=> fix: [2.5] fix list aliases rpc call and grant/revoke v2 

examples/orm/iterator.py, pymilvus/orm/iterator.py
related: #2418
pr: https://github.com/milvus-io/pymilvus/pull/2419
=> extend unlimted offset for query iterator(#2418)

pymilvus/orm/collection.py
=> fix: [2.4]Add is_clustering params for get_compaction_plans in orm

pymilvus/orm/collection.py
=> fix: [2.5]Add is_clustering params for get_compaction_plans in orm

examples/orm/rbac.py, examples/rbac.py, pymilvus/milvus_client/milvus_client.py
=> enhance: [2.4] rbac privilege group and grant v2 examples

examples/orm/rbac.py, examples/rbac.py, pymilvus/milvus_client/milvus_client.py
=> enhance: [2.5] rbac privilege group and grant v2 examples

pymilvus/bulk_writer/buffer.py, pymilvus/bulk_writer/bulk_import.py, pymilvus/bulk_writer/local_bulk_writer.py, pymilvus/bulk_writer/remote_bulk_writer.py, pymilvus/milvus_client/milvus_client.py, pymilvus/settings.py
=> fix: [25]Unify logger and correct logging settings (#2397)

examples/orm/iterator.py, pymilvus/orm/iterator.py
=> enhance: refine query iterator cp(#2412)

pymilvus/client/constants.py, pymilvus/client/prepare.py
issue: https://github.com/milvus-io/milvus/issues/37360
=> enhance: support hints param

pymilvus/bulk_writer/buffer.py, pymilvus/bulk_writer/bulk_import.py, pymilvus/bulk_writer/local_bulk_writer.py, pymilvus/bulk_writer/remote_bulk_writer.py, pymilvus/milvus_client/milvus_client.py, pymilvus/settings.py
=> fix: [24]Unify logger and correct logging settings (#2397)

examples/search_with_template_expression.py
=> enhance: [2.5]Add example for milvus client about expression template

examples/search_with_template_expression.py
=> enhance: [2.4]Add example for milvus client about expression template

pymilvus/client/grpc_handler.py, pymilvus/milvus_client/milvus_client.py
enhance createdatabase support properties
issue: https://github.com/milvus-io/pymilvus/issues/2447
=> enhance: createdatabase support properties

pymilvus/client/grpc_handler.py, pymilvus/milvus_client/milvus_client.py
enhance createdatabase support properties
issue: https://github.com/milvus-io/pymilvus/issues/2447
=> enhance: [2.5] createdatabase support properties

pymilvus/client/grpc_handler.py, pymilvus/client/types.py
fix describe database return type
issue:https://github.com/milvus-io/milvus/issues/38471
=> fix: fix describe database return type

pymilvus/client/grpc_handler.py, pymilvus/client/types.py
fix describe database return type
issue:https://github.com/milvus-io/milvus/issues/38471
=> fix: [2.5]fix describe database return type 

pymilvus/client/grpc_handler.py, pymilvus/client/types.py
fix describe database return type
issue:https://github.com/milvus-io/milvus/issues/38471
=> fix: [2.4]fix describe database return type

examples/simple_async.py, pymilvus/__init__.py, pymilvus/client/async_grpc_handler.py, pymilvus/client/async_interceptor.py, pymilvus/milvus_client/__init__.py, pymilvus/milvus_client/async_milvus_client.py, pymilvus/orm/connections.py
- Support async delete, get, insert, query, search, hybrid_search, upsert, create_collection, drop_collection, describe_collection
- Support adding interceptor to aio channel
- Use `_async_channel.channel_ready()` in `_wait_for_channel_ready` instead of polling logic by `_async_channel.get_state()`
- Add `_async` parameter in `connections.py` to determine whether to establish a synchronous or asynchronous connection
- Update `__init__.py` to allow importing AsyncMilvusClient
- Add a simple code example for AsyncMilvusClient
Signed-off-by: Ruichen Bao <ruichen.bao@zju.edu.cn>
=> feat: [2.5] asyncio support

pymilvus/client/async_grpc_handler.py, pymilvus/orm/connections.py
- Delete code using constant `ITERATOR_SESSION_TS_FIELD`
- Add `_async` parameter in `connections.py` to determine whether to establish a synchronous or asynchronous connection
=> fix: [2.4] resolve conflicts and update connections.py

pymilvus/client/async_grpc_handler.py
- Add `wait_for_creating_index`, `wait_for_loading_collection` to ensure `create_index` and `load_collection` are fully completed
=> fix: ensure `create_index` and `load_collection` are fully completed

examples/search_group_by.py
=> enhance: add search_group_by example for milvus-client(#2481)

examples/search_group_by.py
=> enhance: refine search_group_by_example(#2481)

pymilvus/client/async_grpc_handler.py, pymilvus/orm/connections.py
- Add `wait_for_creating_index`, `wait_for_loading_collection` to ensure `create_index` and `load_collection` are fully completed
=> fix: [2.4] ensure `create_index` and `load_collection` are fully completed

examples/hybrid_search.py, examples/hybrid_search/hybrid_search.py, pymilvus/client/abstract.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/async_milvus_client.py
issue: https://github.com/milvus-io/milvus/issues/38616
=> fix: [2.5]Support hybrid search with expression template

examples/hybrid_search.py, examples/hybrid_search/hybrid_search.py, pymilvus/client/abstract.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/async_milvus_client.py
issue: https://github.com/milvus-io/milvus/issues/38616
=> fix: Support hybrid search with expression template

pymilvus/milvus_client/milvus_client.py
pr: https://github.com/milvus-io/pymilvus/pull/2491
=> enhance: add use_database

examples/alter.py
add alter and drop properties example for alterindex altercollection altercollectionfield
=> enhance: add alter properties example

examples/alter.py
add drop properties example
add alter and drop properties example for alterindex altercollection altercollectionfield
master pr: https://github.com/milvus-io/pymilvus/pull/2504
=> enhance: [2.5]add alter properties example

examples/alter.py
add drop properties exampleadd drop properties example
add alter and drop properties example for alterindex altercollection altercollectionfield
master pr: https://github.com/milvus-io/pymilvus/pull/2504
=> enhance: [2.4]add alter properties example

pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
related: https://github.com/milvus-io/milvus/issues/37031
=> fix: fix privilege typo

pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
cherry-pick from master: https://github.com/milvus-io/pymilvus/pull/2510
related: https://github.com/milvus-io/milvus/issues/37031
=> fix: [2.4] fix privilege typo

pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
cherry-pick from master: https://github.com/milvus-io/pymilvus/pull/2510
related: https://github.com/milvus-io/milvus/issues/37031
=> fix: [2.5] fix privilege typo

examples/database.py
enhance:  add database operation example
=> enhance:  add database operation example

examples/database.py
add database operation example
master pr: https://github.com/milvus-io/pymilvus/pull/2516
=> enhance: [2.5]add database operation example

examples/database.py
add database operation example
master pr: https://github.com/milvus-io/pymilvus/pull/2516
=> enhance: [2.4]add database operation example

pymilvus/exceptions.py
issue: https://github.com/milvus-io/milvus/issues/37548
=> enhance:refine search iter v2 warning

pymilvus/client/search_iterator.py, pymilvus/milvus_client/milvus_client.py
issue: https://github.com/milvus-io/pymilvus/issues/2530
pr: https://github.com/milvus-io/pymilvus/pull/2531
Signed-off-by: Patrick Weizhi Xu <weizhi.xu@zilliz.com>
(cherry picked from commit cd30dc311e98159a6670cedd0fc6bf793669357e)
=> fix: [2.5] fix search iter v2 limit compatibility

pymilvus/client/search_iterator.py, pymilvus/milvus_client/milvus_client.py
=> fix: fix search iter v2 limit compatibility

.github/workflows/publish_dev_package.yml
Ref: https://docs.pypi.org/trusted-publishers/using-a-publisher/
See also: #2440
=> enhance: Publishing with trusted publisher

pymilvus/client/abstract.py, pymilvus/client/types.py, pymilvus/milvus_client/async_milvus_client.py, pymilvus/milvus_client/milvus_client.py, pyproject.toml
issue: https://github.com/milvus-io/milvus/issues/37899
pr: https://github.com/milvus-io/pymilvus/pull/2552
=> enhance: [2.5] support recalls for milvus_client

pymilvus/client/search_iterator.py
issue: https://github.com/milvus-io/milvus/issues/39117
pr: https://github.com/milvus-io/pymilvus/pull/2569
Signed-off-by: Patrick Weizhi Xu <weizhi.xu@zilliz.com>
(cherry picked from commit 8aaa5276a6bf00052c9aceb4aacc6e49f6ba691f)
=> fix: [2.5] use dummy call for search iterator v2 compatibility

pymilvus/client/search_iterator.py
issue: https://github.com/milvus-io/milvus/issues/39117
=> fix: use dummy call for search iterator v2 compatibility

pymilvus/orm/iterator.py
=> fix: unset collection_name for search iterator_v1(#2555)

pymilvus/client/utils.py
=> fix: should not modify users search_param, copy instead

.github/workflows/publish_on_release.yml
Ref: https://docs.pypi.org/trusted-publishers/using-a-publisher/
See also: #2440
=> enhance: Publishing releases with trusted publisher

.github/workflows/publish_on_release.yml
Ref: https://docs.pypi.org/trusted-publishers/using-a-publisher/
See also: #2440
=> enhance: [25]Publishing releases with trusted publisher

.github/workflows/publish_on_release.yml
Ref: https://docs.pypi.org/trusted-publishers/using-a-publisher/
See also: #2440
=> enhance: [24]Publishing releases with trusted publisher

pymilvus/client/abstract.py, pymilvus/client/grpc_handler.py
enhance: Add schema update time verification to insert and upsert to use cache
issue: https://github.com/milvus-io/milvus/issues/39093
=> enhance: Add schema update time verification to insert and upsert to use cache

examples/partition.py, pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
issue: milvus-io/milvus#38983
pr: #2541
=> enhance: enable describe_replica api in milvus client (#2541)

pymilvus/milvus_client/milvus_client.py
enhance: get and delete to use schema cache
issue: https://github.com/milvus-io/milvus/issues/39093
pr: https://github.com/milvus-io/pymilvus/pull/2606
=> enhance: [2.4]get and delete to use schema cache

pymilvus/milvus_client/milvus_client.py
enhance: get and delete to use schema cache
issue: https://github.com/milvus-io/milvus/issues/39093
=> enhance: get and delete to use schema cache

pymilvus/milvus_client/milvus_client.py
enhance: get and delete to use schema cache
issue: https://github.com/milvus-io/milvus/issues/39093
pr: https://github.com/milvus-io/pymilvus/pull/2606
=> enhance: [2.5]get and delete to use schema cache

examples/datatypes/int8_example.py, pymilvus/client/abstract.py, pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/types.py, pymilvus/orm/schema.py, tests/test_abstract.py, tests/test_collection.py, tests/test_schema.py, tests/test_types.py
Issue: https://github.com/milvus-io/milvus/issues/38666
=> enhance: support Int8Vector

.github/workflows/check_milvus_proto.yml, .github/workflows/code_checker.yml, .github/workflows/nightly_ci.yml, .github/workflows/pull_request.yml
=> fix: Use ubuntu22.04 instead of latest

pymilvus/orm/iterator.py
=> fix: remove set batchsize to ef for param flat(#2626)

pymilvus/client/utils.py
issue: https://github.com/milvus-io/milvus/issues/39791
=> fix: fix query int8_vector

examples/bulk_import/example_bulkwriter.py, pymilvus/bulk_writer/bulk_writer.py, pymilvus/bulk_writer/constants.py, pymilvus/bulk_writer/validators.py, pymilvus/client/async_grpc_handler.py, pymilvus/client/entity_helper.py, pymilvus/client/utils.py
issue: https://github.com/milvus-io/milvus/issues/39847
=> Support bulk insert for INT8_VECTOR

pymilvus/client/abstract.py
enhance: describecollection output add created_timestamp
issue: https://github.com/milvus-io/pymilvus/issues/2617
=> enhance: describecollection output add created_timestamp

examples/iterator/iterator.py, pymilvus/client/search_iterator.py, tests/test_search_iterator.py
issue: https://github.com/milvus-io/milvus/issues/39914
=> feat: add external filter func for search iterator v2

pymilvus/client/types.py, tests/test_types.py
=> fix: Unify output of str(DataType) for different pythons (#2635)

pymilvus/client/grpc_handler.py
https://github.com/milvus-io/pymilvus/issues/2646
=> grpc thread is not released each time connections.connect() is failed

pymilvus/client/abstract.py
enhance: describecollection output add created_timestamp
issue: https://github.com/milvus-io/pymilvus/issues/2617
pr: https://github.com/milvus-io/pymilvus/pull/2618
=> enhance: [2.4]describecollection output add created_timestamp

examples/bulk_import/example_bulkwriter_with_nullable.py, pymilvus/bulk_writer/bulk_writer.py
https://github.com/milvus-io/pymilvus/issues/2654
=> Fix bug for BulkWriter with nullable/default_value fields

pymilvus/client/entity_helper.py
issue: https://github.com/milvus-io/milvus/issues/39930
=> fix: correct Int8Vector handle wrong insert data type

pymilvus/exceptions.py, pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/35856
=> feat: Text embedding supports int8 vector

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py
=> fix: [cp25]Add and check timeout param in database api

pymilvus/client/grpc_handler.py
pr: https://github.com/milvus-io/pymilvus/pull/2677
=> fix: Remove field check in create_index (#2677)

pymilvus/client/grpc_handler.py
This reverts commit b2bca89faa52357f2ad9ca781bc9a06e6e4105b0.
=> Revert "enhance: Convert json_cast_type to DataType (#2690)"

pymilvus/client/abstract.py
=> fix: Remove not useful SequenceIterator

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py
- issue: https://github.com/milvus-io/milvus/issues/40843
=> enhance: Add force_drop parameter to drop_role method for role deletion

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py
- issue: https://github.com/milvus-io/milvus/issues/40843
- pr: #2705
=> enhance: [2.5] Add force_drop parameter to drop_role method for role deletion

examples/hybrid_search.py, examples/hybrid_search/hybrid_search.py, pymilvus/client/abstract.py
issue: https://github.com/milvus-io/milvus/issues/40836
=> weighted reranker to allow skip score normalization

examples/hybrid_search.py, examples/hybrid_search/hybrid_search.py, pymilvus/client/abstract.py
pr: https://github.com/milvus-io/pymilvus/pull/2708
issue: https://github.com/milvus-io/milvus/issues/40836
=> [2.5] weighted reranker to allow skip score normalization

pymilvus/milvus_client/milvus_client.py, pymilvus/orm/connections.py
It would be more helpful what is unit of timeout in constructor
=> doc: add time unit for constructor

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/decorators.py
Related to milvus-io/milvus#41357
=> enhance: Use hyphen instead of underscore in grpc header

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/decorators.py
Cherry-pick from master
pr: #2730 
Related to milvus-io/milvus#41357
=> enhance: [2.5] Use hyphen instead of underscore in grpc header (#2730)

pymilvus/orm/types.py, pyproject.toml
=> fix: Remove deprecated numpy.bool8

pymilvus/orm/types.py, pyproject.toml
=> fix: [2.5]Remove deprecated numpy.bool8

pymilvus/client/prepare.py, pymilvus/orm/constants.py, pymilvus/orm/schema.py
pr: https://github.com/milvus-io/pymilvus/pull/2747
=> feat:[2.5] suppoprt multi analyzer params (#2747)

pymilvus/client/prepare.py, pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/41526
https://github.com/milvus-io/milvus/issues/41524
=> Add funciton checker

pymilvus/client/async_grpc_handler.py, pymilvus/client/prepare.py
- Solve the problem that the `expr_params` parameter of `async hybrid_search` is not effective
- Solve the problem of rerank parameter verification
=> Fix hybrid search params check

pymilvus/orm/schema.py
https://github.com/milvus-io/pymilvus/issues/2769
=> Fix function construct bug

pymilvus/client/abstract.py
Related to milvus-io/milvus#41639 milvus-io/milvus#41681 milvus-io/milvus#41688
=> fix: Handle collection schema update timestamp

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py
Related to milvus-io/milvus#41688
=> fix: Update schema and retry when data not match

pymilvus/client/prepare.py
=> fix: [cp25]load collection with resource group

pymilvus/client/prepare.py
=> fix: load collection with resource group

pymilvus/milvus_client/milvus_client.py
Related to milvus-io/milvus#39718
=> enhance: [AddField] Use functional signature for add_collection_field

pymilvus/client/async_grpc_handler.py, pymilvus/orm/connections.py, tests/test_collection.py, tests/test_connections.py
Should be helpful to solve the DNS resolve problem
=> enhance: Set keep_alive check by default

pymilvus/client/prepare.py
Related to milvus-io/milvus#42033
=> fix: Pass element type param when converting field schema

pymilvus/client/prepare.py, pymilvus/orm/schema.py
relate: https://github.com/milvus-io/milvus/issues/41804
=> fix: wrong marshal field schema prarams case alter collection failed

pymilvus/client/prepare.py, pymilvus/orm/schema.py
pr: https://github.com/milvus-io/pymilvus/pull/2790
relate: https://github.com/milvus-io/milvus/issues/41804
=> fix:[2.5] wrong marshal field schema prarams case alter collection failed

pymilvus/client/grpc_handler.py
Cherry-pick from master
pr: #2818 
Related to milvus-io/milvus#42138
=> fix: [2.5] Pass correct number of params of _prepare_row_upsert_request

pymilvus/client/async_grpc_handler.py, pymilvus/client/search_result.py, pymilvus/orm/connections.py, tests/test_collection.py, tests/test_connections.py, tests/test_search_result.py
- enhance: Set keep_alive check by default (#2783)
- Fixes hasattr checks against Hit for missing attributes (#2806)
=> enhance: Multiple Cherry picks from master

pymilvus/client/prepare.py
=> feat: support load collection/partition with priority(#2835)

pymilvus/client/prepare.py, pymilvus/orm/schema.py
pr: https://github.com/milvus-io/pymilvus/pull/2844
=> enahnce:[2.5] dump analyzer params when init field schema

pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/client/utils.py
=> enhance: optimize perf for large topk(#2848)

pyproject.toml
=> fix: Bypass FD shutdown by downgrading grpc to <1.68.0

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/client/search_result.py, pymilvus/client/types.py
=> fix: hybridExtraList miss iter method

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/client/search_result.py, pymilvus/client/types.py
related: #2848
pr: https://github.com/milvus-io/pymilvus/pull/2862
=> fix: hybridExtraList miss iter method and dynamic fields value overrite fixed field value(#2848)

pymilvus/client/search_result.py, pymilvus/client/types.py
=> enhance: make query result mutable for only one time modification

pymilvus/client/async_grpc_handler.py
issue: https://github.com/milvus-io/milvus/issues/42968
master pr: #2762
=> fix: Fix hybrid search params check

pymilvus/client/entity_helper.py
issue: https://github.com/milvus-io/pymilvus/issues/2886
=> fix: refine error message

pymilvus/milvus_client/milvus_client.py
issue: https://github.com/milvus-io/milvus/issues/25397
=> fix: Return new pk value for upsert when autoid=true

.github/workflows/update-milvus-pymilvus-dev.yml
=> fix: Correct token usage 

.github/workflows/update-milvus-pymilvus-dev.yml
fix this: pull request create failed: GraphQL: Head sha can't be blank, Base sha can't be blank, Head repository can't be blank, No commits between milvus-io:master and
Milvus:bot/pymilvus-update-for-master-2.7.0.rc19-20250827110012, Head ref must be a branch, not all refs are readable
And sign-off the commit
=> enhance: Make pr to fix the empty head error

.pre-commit-config.yaml, Makefile, README.md, pymilvus/client/interceptor.py
See also: milvus-io/milvus#44058
=> enhance: Add unixmsec in every RPC call

pymilvus/client/async_grpc_handler.py, pyproject.toml, tests/test_async_grpc_handler.py
=> fix: Passing unknown req.is_refresh to wait

pymilvus/client/async_grpc_handler.py, pyproject.toml, tests/test_async_grpc_handler.py
add pytest-asyncio to dev packages 
See also: #2796, #2963
=> fix: [2.5]Passing unknown req.is_refresh to wait 

.github/workflows/pull_request.yml
=> enhance: [2.6]Run actions when push to repo to enable cov compare

pymilvus/client/types.py
=> enhance: [2.6] update get_cost_from_status

pymilvus/client/abstract.py, pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/client/search_result.py, pymilvus/client/types.py, pymilvus/client/utils.py, pymilvus/orm/partition.py, pymilvus/orm/schema.py, pyproject.toml, tests/test_search_result.py
this PR adresses this issue: https://github.com/milvus-io/pymilvus/issues/1354
=> enhance: Replace ujson with orjson

pymilvus/__init__.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/collection.py, pymilvus/orm/schema.py
pr: https://github.com/milvus-io/pymilvus/pull/2992
=> feat: [2.6] support use function scorer as ranker not one function
