milvus-io/pymilvus

requirements.txt
Bumps:
- jinja2 from 2.10.3 to 2.11.3.
- pygments from 2.5.2 to 2.7.4.
- py from 1.8.1 to 1.10.0.
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump jinja2 pygments and py

setup.py
The dependency does not seem to be needed during the setup.py. I noticed it while building a conda forge package for pymilvus at https://github.com/conda-forge/staged-recipes/pull/14772
=> Remove git dep in setup.py

.github/workflows/release_event.yml
Add new action "release_event.yml" to dispatch release published event to Milvus doc repo(refer to https://github.com/milvus-io/docs/blob/master/.github/workflows/updateApiReference.yml)
=> Create release_event.yml to dispatch release published event to Milvus doc repo

pymilvus/client/grpc_handler.py, pymilvus/settings.py
Resolves milvus-io/milvus#6625
According to the comments [here](https://github.com/milvus-io/pymilvus/blob/547ff0f6f8dc266bbc4e31ecedb2ed7bc1402106/pymilvus/client/abs_client.py#L551), the default metric used for calc_distance should be "L2". However, calling this function through pymilvus or pymilvus_orm results in an error, as seen in milvus-io/milvus#6625
This PR sets the default to be "L2", configurable in the settings. 
There are multiple places that this could have been implemented, such as in the milvus-io/milvus repository instead of here. Let me know if there's a better place for the default check to be made. 
Signed-off-by: NotRyan <ryan.chan@zilliz.com>
=> Set default calc_distance metric to "L2"

.github/workflows/doc_update_event.yml, .github/workflows/release_event.yml
- Update latest repo url from `doc` to `web-content`
- Add docs update event. Any modifies under `docs/` should dispatch event action to `web-content` for consistent update.
=> Update workflows for web-content

examples/old_style_example.py, examples/old_style_example_distance.py, examples/old_style_example_index.py
This PR fixes create collection dup metric type (#649)
Fix lint in examples:
- Expect 2 blank lines, found 1
- Missing whitespace around arithmetic operator
- Unexpected spaces around keywork/parameter equals
=> Fix not runnable examples

pymilvus/client/abstract.py
In reference to #701.
This adds a __str__ method to baseloop, which is a parent of our hits object. Now hits can be printed directly, which will simply list out a string representation of all the contents. See image below. 
Signed-off-by: NotRyan <ryan.chan@zilliz.com>
=> Adds __str__ for baseloop (Search results)

pymilvus/orm/search.py
Adds __str__ methods to ORM versions of the SearchResult and Hits objects. They print out the string of the objects they contain; capped at a maximum of 10 if there are more than that.
Signed-off-by: NotRyan <ryan.chan@zilliz.com>
=> Add __str__ methods to orm SearchResult and Hits objects

pymilvus/orm/search.py
Currently, getting the contents of an ORM SearchResult or an ORM Hits object will result in a differently typed version of the contents depending on whether the get is done with a slice or an index. See this image for an example:
It does not make sense for one to return objects of different types; logically they should be the same. This PR changes it so that all objects are returned as the corresponding ORM type. See the following image: 
If we would rather have the objects return the other type, let me know and I can change it to that. But whatever they are, it should be consistent. 
Signed-off-by: NotRyan <ryan.chan@zilliz.com>
=> Update ORM SearchResult and Hits objects to use consistent types for index gets and slice gets

docs/source/api/utility.rst, examples/collection.py, pymilvus/orm/collection.py, pymilvus/orm/utility.py, requirements.txt
Aliases are targeted for multi-collection switching,
it seems wierd to bind aliases operations within `Collection`.
This PR mvs aliases operations into `utility`
=> Move aliases operations into utility

pymilvus/client/grpc_handler.py, tests/conftest.py, tests/test_grpc_handler.py
Note grpc_testing doesn's support EXPERIMENTAL apis
such as `wait_for_ready`.
See also: #985
=> Add unittests framework for grpc_handler

pymilvus/client/grpc_handler.py, pymilvus/decorators.py, tests/e2e_issues/test_issue_16835.py
- Add the corresponding e2e issue cases
- `wait_for_ready` is an experimental API in grpc, causes
API hanging forever of the server failed. So remove this
from search.
- Remove some not in-used search methods
See also: milvus-io/milvus#16835
=> Fix seach hangs forever while server unavaliable

.github/mergify.yml
=> Fix mergify unable to label ci-pass on branch 2.0

pymilvus/client/grpc_handler.py, pymilvus/client/stub.py, pymilvus/decorators.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, pymilvus/orm/utility.py
1. Enable timeout to control retry times (#1012)
- Make sure ever timeout parameter is the last position param
- Remove check_has_collection
- Enable timeout to control retry times
2. Fix nightly index out of range (#1016)
- Get rid of dagerous args slice
- Make sure all the API passes timout by kwargs form
`search(..., timeout=timeout)`
See also: #16853
Fixes: #1015
=> Cherry pick of (#1012) and (#1016)

README.md, requirements.txt, setup.py
To run pymilvus, we only need `grpcio`
To generate python files from protos, we need `grpcio-tools`
This PR:
1. Removes `grpcio-tools` from install requirements
2. Extends `grpcio` versions
3. Provides the compatible version ranges of `grpcio-tools` and `grpcio`
See also: #1030, #943, #946
=> Extend grpcio version requirements range

requirements.txt, setup.py
ujson 5.4.0 is required to resolve https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-31116
> UltraJSON is a fast JSON encoder and decoder written in pure C with bindings for Python 3.7+. Affected versions were found to improperly decode certain characters. JSON strings that contain escaped surrogate characters not part of a proper surrogate pair were decoded incorrectly. Besides corrupting strings, this allowed for potential key confusion and value overwriting in dictionaries. All users parsing JSON from untrusted sources are vulnerable. **From version 5.4.0, UltraJSON decodes lone surrogates in the same way as the standard library's `json` module does, preserving them in the parsed output. Users are advised to upgrade.** There are no known workarounds for this issue.
=> Fix CVE-2022-31116 by allow upgrade ujson include 5.4.0

pymilvus/client/stub.py
=> Don't set default_idx as index name when drop index

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, tests/test_prepare.py
Signed-off-by: Li Liu <li.liu@zilliz.com>
This PR fix some low efficient code:
1. Call `to_dict()` of a collection at construction time and store it for search use.
2. Use a map instead of endless `if else` to check param.
3. For sync search, simply use serial execution instead of `async + get`
4. Remove deep copy in search path
For performance enhancement, I did some test in my 2C8M container:
*Pymilvus*: Set `grpc` to return empty response immediately, the QPS of `Pymilvus` increase from ~1200 to ~2100, increased about 75%
*End 2 End*: For nq1 serial execution, latency improved ~10%.
Notice: Still lots of similar style in other parts of the code, like deep copy, `to_dict()` call, `if else` param check and mixed sync/async call. We need to fix them all if needed.
=> Optimize some low efficient code

examples/example_bulkinsert.py, pymilvus/orm/utility.py
=> Modify bulkinsert example

README.md
=> Update Readme to the latest pymilvus version

examples/example.py
=> Enhance expression of search

examples/resource_group.py, pymilvus/__init__.py, pymilvus/client/grpc_handler.py
=> fix load collection

examples/resource_group.py, pymilvus/__init__.py, pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/decorators.py, pymilvus/orm/connections.py, pymilvus/orm/default_config.py
- Fix not checking replica_number in load (#1266)
- Fix not check replica_number when load_partitions (#1271)
- Change default connect timeout to 10s (#1294)
- Fix describe/list rg err msg (#1291)
- Fix load collection (#1293)
See also: milvus-io/milvus#21618
=> Multi cherryp-pick to sync master and 2.2

pymilvus/client/entity_helper.py
a quick fix for bug https://github.com/milvus-io/pymilvus/issues/1143
=> fix can't insert string == schema max len

pymilvus/grpc_gen/python_gen.sh, setup.py
- Improvement support colab (milvus-io#1353)
- Fix missing dependency with protobuf (milvus-io#1358)
Google colab notebook already installed protobuf==3.20.3 at the moment.
And installing grpcio-tools will request a higher version protobuf.
So a restart for notebook kernel is needed.
Indeed grpcio-tools is not mandatory for pymilvus.
Issue: milvus-io#1356
Co-Authored-By: Ji Bin <matrixji@live.com>
=> Multi cherry-picks of 2.2

pymilvus/client/grpc_handler.py, pymilvus/client/stub.py, pymilvus/client/utils.py, pymilvus/orm/utility.py, tests/test_utils.py
=> Add an utility to get server type

pymilvus/orm/utility.py
=> List indexes by field name

pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py
=> Sync partiton APIs with collection

pymilvus/milvus_client/defaults.py, pymilvus/milvus_client/milvus_client.py, pymilvus/milvus_client/milvus_client_tests.py, requirements.txt
Looking to add a wrapper around Pymilvus for easier usage.
=> Milvus Client

pymilvus/__init__.py, pymilvus/milvus_client/milvus_client.py
For the release notes here is a snipped example:
```python
from pymilvus import MilvusClient
client = MilvusClient(
collection_name="qux",
uri="http://localhost:19530",
vector_field="float_vector",
overwrite=True,
)
data = [
{
"float_vector": [1,2,3],
"id": 1,
"text": "foo"
},
{
"float_vector": [4,5,6],
"id": 2,
"text": "bar"
},
{
"float_vector": [7,8,9],
"id": 3,
"text": "baz"
}
]
client.insert_data(data)
res = client.search_data(
data = [1,3,5],
top_k = 2,
filter_expression= "id > 1"
)
```
=> Few fixes before 2.2.8 cherrypick

pymilvus/client/entity_helper.py, pymilvus/client/types.py, pymilvus/orm/types.py
/kind feature
related https://github.com/milvus-io/pymilvus/issues/1370
=> Support insert dict as JSON (#1424)

pymilvus/client/abstract.py, pymilvus/client/grpc_handler.py
/kind bug
related https://github.com/milvus-io/milvus/issues/24144 https://github.com/milvus-io/milvus/issues/24132
=> Fix lost JSON result

pymilvus/orm/connections.py
None user/password breaks the length check that occurs. This is for backwards compatibility.
=> Fix None user/password

pymilvus/orm/connections.py
Currently secure is only deduced if a uri is passed in with username/pass. It should deduce in any case where user and password are provided.
=> deduce secure from user/pass

pymilvus/client/prepare.py, pymilvus/client/stub.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/collection.py, tests/test_prepare.py
The user can still use shards_num to create collection. But shards_num are the recommanded way to create collection and the only way to get from a collection's property
See also: milvus-io/milvus#23853
=> Unify num_shards and mark shards_num as deprecated

pymilvus/client/prepare.py, pymilvus/orm/collection.py
See also: #1610, milvus-io/milvus#25587
=> Support offset in search param

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/stub.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py
issue: https://github.com/milvus-io/milvus/issues/26070
=> Remove time travel params

pymilvus/client/check.py
When I want add a new index like scann(https://github.com/milvus-io/milvus/pull/26099), seems we do not need to add index support in pymilvus(all the check would be done in milvus), but the check functions still exist, just remove them.
=> Remove unused index and metric_type check

pymilvus/orm/schema.py
When names and fields from a dataframe(received) are compared against those of a collection(expected), the name match check  should be done first before type match check.
Otherwise, when the dataframe and collection have different number of fields, or different ordering of the fields, a type mismatch error message could be logged, which is more misleading than a name miss match error.
=> Unmask dataframe field name mismatch error

pyproject.toml
"no-guess-dev" will add a post1.devN to the commit
```
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
32
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
33
'2.3.0b1.dev124+g71b52fc' is an invalid value for Version. Error: Can't
34
use PEP 440 local versions. See                                        
35
https://packaging.python.org/specifications/core-metadata for more     
36
information.   
```
=> Fix semver not match pep440

pymilvus/orm/connections.py
/kind bug
[milvus #26833](https://github.com/milvus-io/milvus/issues/26833)
|||default value| user case1(as bug described)|user case2|user case 3|user case4|
|--|--|--|--|--|--|--|
|MilvusClient's arguments|uri|http://localhost:19530|http://localhost:19530|http://localhost:19530/test|http://localhost:19530/test|http://localhost:19530/test|
||db_name||test||default|test|
|connect with milvus server||found uri without dbname, use "default"|found uri without dbname, use "default"|found uri with dbname "test"|found uri with dbname "test"|found uri with dbname "test"|
|result||correct|**db_name didn't work**|corrent|uri priority higher|corrent|
|how to fix|||use db_name "test"|||||
=> while parse uri, overwrite the db_name with default

examples/example_bulkwriter.py, pymilvus/bulk_writer/bulk_writer.py
https://github.com/milvus-io/pymilvus/issues/1710
=> Support numpy type value for bulkwriter

pymilvus/orm/constants.py, pymilvus/orm/iterator.py
=> add judgement for isPrimary

pymilvus/client/abstract.py, pymilvus/orm/future.py
1. Print id instead of pk
2. Return the correct data type for future.result()
=> Fix search result

pymilvus/client/grpc_handler.py, pymilvus/orm/schema.py
For Milvus2.2.x, PyMilvus needs to check for `error_code` before checking codes, cuz code will alwasy returns 0, which indicates rpc success
=> Fix has_collection result with Milvus2.2

pymilvus/orm/role.py
=> [Cherry-Pick]: Improve the default db for the rbac (#1752)

pymilvus/orm/utility.py
fix issue https://github.com/milvus-io/pymilvus/issues/1764
load_state parameter `partition_names` error
=> fix: load_state parameter type err

examples/hello_milvus_simple.py, pymilvus/milvus_client/milvus_client.py
Starting from version 2.3.2, Milvus no longer includes the primary keys in the result when processing the delete operation with expressions. This change is due to the large amount of data involved. The delete interface no longer returns any results. If no exceptions are thrown, it indicates a successful deletion. However, for backward compatibility, if the primary_keys returned from Milvus is not empty the list of primary keys is still returned.
=> Modify highlevel delete to not return any value

examples/hello_milvus_delete.py, pymilvus/exceptions.py, pymilvus/milvus_client/milvus_client.py
Commencing from Milvus 2.3.3, an enhanced functionality has been introduced to facilitate data deletion based on expressive criteria. In this context, the inclusion of the "filter" parameter serves as an entry point for accessing this feature.
All rows that conform to the specified filter expression will be eliminated.
Moreover, in cases where users specify both a list of primary keys to be deleted and provide a filter expression, the deletion operation will encompass the union of these two conditions, resulting in the removal of rows that satisfy either criterion.
=> Add filter parameter to delete

pymilvus/orm/iterator.py
=> search iterator support range-search paramter(#1793)

pymilvus/client/grpc_handler.py
This PR fix wrong usage of check_status in create_alias.
issue: https://github.com/milvus-io/pymilvus/issues/1804
=> fix: Fix check_status for create_alias func

pymilvus/client/check.py, pymilvus/client/utils.py
issue:issue:https://github.com/milvus-io/milvus/issues/29230
=> add gpu_cagra index in pymilvus

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py
related: https://github.com/milvus-io/milvus/issues/21866
=> feat: support alter index

pymilvus/client/grpc_handler.py, pymilvus/orm/connections.py
=> Auto reconnection when channel state changed to idle

pymilvus/orm/iterator.py
=> fix: to avoid zero value for width

pymilvus/exceptions.py, pymilvus/milvus_client/milvus_client.py
related with https://github.com/milvus-io/milvus/issues/30094
=> fix: change confusing error message

pymilvus/exceptions.py, pymilvus/orm/iterator.py
fix: to avoid zero value for width (#1855)
fix: change confusing error message (#1881)
=> Multi-cherry bug fixes from master

examples/hello_sparse.py, examples/milvus_client/sparse.py, pymilvus/client/abstract.py, pymilvus/client/check.py, pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/types.py, pymilvus/client/utils.py, pymilvus/exceptions.py, pymilvus/orm/collection.py, pymilvus/orm/iterator.py, pymilvus/orm/partition.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py, pymilvus/orm/types.py, requirements.txt
This PR adds the basic sparse float vector support to pymilvus. 
The following types of input are supported:
- any of the `scipy.sparse` matrix/array class family
- list of dicts: `[{0: 0.3, 20: 0.5}, {4: 0.4}, ...]`
- list of lists of tuples: `[[(0, 0.3), (20, 0.5)], [(4, 0.4)], ...]`
Sparse float vector support tracking issue: https://github.com/milvus-io/milvus/issues/29419
=> feat: Add sparse float vector support to PyMilvus

pymilvus/client/entity_helper.py
non-empty list with empty rows(row with 0 non-zero value) will also not be inferred as sparse vector input, as no sparse vector related API allows empty sparse row.
=> sparse float vector: do not infer empty list as sparse vector input

pymilvus/orm/schema.py
to avoid such param error:
```
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=Collection field dim is 512, but entities field dim is 512)>
```
=> covert params' value from string to int

pymilvus/orm/schema.py
master pr: #2022
to avoid such param error:
```
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=Collection field dim is 512, but entities field dim is 512)>
```
=> [cherry-pick] covert params' value from string to int

pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/orm/collection.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py, pyproject.toml
=> fix: restrict input/search type for vector fields

pymilvus/client/grpc_handler.py, pymilvus/decorators.py
Reverts milvus-io/pymilvus#1976
=> Revert "enhance: retry on inconsistent requery (#1975)"

pymilvus/bulk_writer/buffer.py
When import via bulkwriter, for array type, we should specify datatype; otherwise, it will default to double(for float32 array) and int64(for int8, int16, int32 array).
issue: https://github.com/milvus-io/pymilvus/issues/2034, https://github.com/milvus-io/milvus/issues/31834
=> fix: Fix import array via bulkwriter

pymilvus/bulk_writer/buffer.py
When import via bulkwriter, for array type, we should specify datatype; otherwise, it will default to double(for float32 array) and int64(for int8, int16, int32 array).
issue: https://github.com/milvus-io/pymilvus/issues/2034, https://github.com/milvus-io/milvus/issues/31834
pr: https://github.com/milvus-io/pymilvus/pull/2035
=> fix: Fix import array via bulkwriter (#2035)

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/stub.py, pymilvus/orm/collection.py
=> feat: Support major compaction in ManualCompaction

pymilvus/client/entity_helper.py
so that the error messages can correctly propagate
=> Change sparse related errors to ParamError

examples/example_tls1.py
It is to make the example consistent with https://milvus.io/docs/tls.md.If these changes look fine I can modify the other example as well
=> modified example_tls1.py through MilvusClient

examples/example_tls2.py
It is to make the example consistent with [https://milvus.io/docs/tls.md.](https://milvus.io/docs/tls.md.If).
=> modified example_tls2.py through MilvusClient

examples/example_tls1.py, examples/example_tls2.py, pymilvus/orm/schema.py
Fix bug: add enable_dynamic_field in result of DescribeCollection (#1949)
1. modified example_tls1.py through MilvusClient (#2065)
2. modified example_tls2.py through MilvusClient (#2077)
3. It is to make the example consistent with milvus.io docs
=> enhance: Cherry pick #1949, #2065, #2077

examples/example_bulkwriter.py, pymilvus/__init__.py, pymilvus/bulk_writer/__init__.py, pyproject.toml
=> enhance: [2.4]Make bulk_writer's requirments optional (#2086)

examples/hello_cost.py, examples/milvus_client/simple_cost.py, pymilvus/client/abstract.py, pymilvus/client/asynch.py, pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/mutation.py
issue: https://github.com/milvus-io/milvus/issues/30436
=> [2.4] support the report value in the dml and dql request

pymilvus/client/entity_helper.py
when providing sparse float vector using python dict/list, we allow the index/value to be wrapped in string:
both `{1:0.1, 2:0.2}` and `{1:"0.1", "2": 0.2}` are acceptable. this is defined in `entity_is_sparse_matrix` but `sparse_rows_to_proto` doesn't respect this. This pr fixes this.
=> fix sparse: accpet int/float wrapped in string

pymilvus/orm/connections.py
Added grpc protocol to connection uri validation. Not having it was preventing grpc connections with the following error: <ConnectionConfigException: (code=1, message=Open local milvus failed, dir: grpc: is not exists)>
=> Added grpc as a valid protocol for uri

pymilvus/client/entity_helper.py
previous:
```
col.insert([[1, 2, 3], csr]) # ok if csr is a 3 row sparse object
col.insert([[1, 2, 3], [csr1, csr2, csr2]]) # this is not ok
```
now:
```
col.insert([[1, 2, 3], [csr1, csr2, csr2]]) # ok if csr1/csr2/csr3 are all single row object
```
=> Accept list of single row scipy.sparse object as input for insert/search

pyproject.toml
@XuanYang-cn 
Since the project is managed by setuptools, and according to the [setuptools](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html), we can disable the automatic installation of milvus-lite on windows platform by adding environment markers. 
Following [PEP508](https://peps.python.org/pep-0508/), I pick the environment marker "sys_platform != 'win32'" to prevent the installation. 
I build packages after the modification. Then test the .tar.gz and the .whl files both on my windows laptop and a linux docker. The issue mentioned in #2131 seems gone. 
Due the lack of macOS machine, I could not perform testing on that particular platform. Please check validity before merging.
=> feat: disable installation of milvus-lite on windows platform (#2131)

.github/workflows/check_milvus_proto.yml, .github/workflows/code_checker.yml, .github/workflows/pull_request.yml, Makefile, pyproject.toml, tests/test_milvus_lite.py
Since the project is managed by setuptools, and according to the
[setuptools](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html),
we can disable the automatic installation of milvus-lite on windows
platform by adding environment markers.
Following [PEP508](https://peps.python.org/pep-0508/), I pick the
environment marker "sys_platform != 'win32'" to prevent the
installation.
I build packages after the modification. Then test the .tar.gz and the
.whl files both on my windows laptop and a linux docker. The issue
mentioned in #2131 seems gone.
Due the lack of macOS machine, I could not perform testing on that
particular platform. Please check validity before merging.
enhance: Check PyMilvus on Windows platform
=> feat: Disable installation of milvus-lite on windows platform

.github/mergify.yml, pymilvus/orm/index.py
Index name and field name is already there for Index object, No need to get them from kwargs when drop
```python
ivf_flat = Index(c, "embeddings", params, index_name="ivf_flat",
construct_only=True)
ivf_flat.drop()
```
=> enhance: update milvus-proto and correct index.drop()

pymilvus/client/constants.py, pymilvus/client/prepare.py
=> feat: support group_size parameter for search_group_by

pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/exceptions.py
=> Refine the error message for type mismatches during data insertion

pymilvus/client/entity_helper.py, pymilvus/client/prepare.py, pymilvus/exceptions.py
=> Refine the error message for type mismatches during data insertion (#2156)

pymilvus/orm/collection.py, pymilvus/orm/partition.py
=> enhance: Remove the logic to set replica_number=1 by default

pymilvus/milvus_client/milvus_client.py
Allows the following operations to be performed through the `MilvusClient` interface:
- create_database
- drop_database
- list_databases
Resolves https://github.com/milvus-io/pymilvus/issues/2151
=> Add database operations to MilvusClient (#2152)

pymilvus/orm/iterator.py
The comment mentions the wrong method name
=> Fix comment in iterator implementation

pymilvus/exceptions.py, pymilvus/orm/schema.py, tests/test_create_collection.py
=> fix: remove limitation clustering key can not be primary key

examples/milvus_client/simple_cost.py, pymilvus/client/abstract.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
=> enhance: hide zero values ​​when printing

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/client/stub.py, pymilvus/orm/collection.py
=> Rename is_major to is_clustering

pymilvus/client/grpc_handler.py, pymilvus/orm/collection.py
Previously added parameters for `load` API have leading underscore, which is misused and copied from `_async` parameter. The leading "_" is to avoid use python keyword `async` and other parameters do not have to follow this pattern.
This PR make `load` API support parameter with or without leading underscore and update related comment. Note that the ones without leading "_" have higher priority than the ones with it.
=> enhance: Make load parameter naming normal

pymilvus/client/grpc_handler.py, pymilvus/orm/collection.py
Previously added parameters for `load` API have leading underscore, which is misused and copied from `_async` parameter. The leading "_" is to avoid use python keyword `async` and other parameters do not have to follow this pattern.
This PR make `load` API support parameter with or without leading underscore and update related comment. Note that the ones without leading "_" have higher priority than the ones with it.
=> enhance: [2.4] Make load parameter naming normal (#2243)

pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py, tests/test_prepare.py
issue: https://github.com/milvus-io/milvus/issues/35464
Signed-off-by: Patrick Weizhi Xu <weizhi.xu@zilliz.com>
(cherry picked from commit 358d0dc5bd4ed2bbfec1dd1eb28d98ed246a4dfe)
=> fix: [2.4] move page_retain_order to the same level as radius

pymilvus/orm/constants.py
the API for `enable_match` has changed to: only VarChar fields that set `enable_tokenizer=true`, is allowed to set `enable_match=true`, or to be used as a BM25 Function input field. Params for such tokenizer is renamed from `analyzer_params` to `tokenizer_params`.
=> remove analyzer_params, added enable_tokenizer and tokenizer_params

pymilvus/settings.py, pyproject.toml, requirements.txt
related #2166.
This PR will replace `environs` with the more lightweight `python-dotenv`. It can load configuration from the dot env file without altering the system environment.
=> feat(pymilvus/settings.py): Load configuration without altering the environment

pymilvus/client/prepare.py, tests/test_prepare.py
https://github.com/milvus-io/milvus/issues/36710
=> fix: upsert rows when set autoid==true fail

pymilvus/bulk_writer/local_bulk_writer.py, pymilvus/client/asynch.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/decorators.py, pymilvus/orm/collection.py, pymilvus/orm/schema.py, pymilvus/orm/utility.py, tests/test_prepare.py
https://github.com/milvus-io/milvus/issues/36710
=> fix: upsert rows when set autoid==true fail(#2286)

examples/hello_bm25.py, examples/hello_hybrid_bm25.py, examples/milvus_client/bm25.py, pymilvus/__init__.py, pymilvus/client/abstract.py, pymilvus/client/check.py, pymilvus/client/prepare.py, pymilvus/client/types.py, pymilvus/exceptions.py, pymilvus/orm/constants.py, pymilvus/orm/prepare.py, pymilvus/orm/schema.py
currently only BM25 Function is supported.
issue: https://github.com/milvus-io/milvus/issues/35853
=> support new Function feature

pymilvus/client/entity_helper.py
currently pymilvus supports the following sparse vector formats:
* scipy sparse classes
* list of tuples: `[(dim, val), (dim, val), ...]`
* dict: `{dim: val, dim: val, ...}`
When dealing with input data, pymilvus doesn't check the schema to infer the data type, instead it tries to infer the data type based on the shape. that's why we have `entity_is_sparse_matrix` method.
Now we want to support empty sparse vector row, it is easy for scipy sparse classes, but for the other 2 format, it means we must infer empty list/dict `[]/{}` as sparse vector. 
Will this be problematic? what could be the other options?
=> feat: allow empty sparse row

pymilvus/exceptions.py, pymilvus/orm/schema.py
this check was added in https://github.com/milvus-io/pymilvus/pull/2257. 
this caused an test in milvus to fail. the test expects the error to be thrown on server side instead of sdk side. it is ok to check on sdk side but I choose to remove it to keep the behavior consistent and comfort the ut without modifying it. 
Failed test: https://github.com/milvus-io/milvus/blob/5b2658327d676453e8a251ffc3273f4a218fb278/tests/python_client/testcases/test_collection.py#L318
=> fix: remove duplicate field name check in pymilvus

pymilvus/orm/iterator.py
=> enhance: enable compatible for iterator(#2278)

examples/example_bulkwriter.py, pymilvus/bulk_writer/bulk_import.py
pr: https://github.com/milvus-io/pymilvus/pull/2295
=> enhance: Enable bulkwriter to support import v2 (#2295)

pymilvus/client/prepare.py, pymilvus/orm/schema.py
also fix schema comparison of tokenizer_params: tokenizer_params returned by the server is in string format, while the user may provide it in dict format. But this fix is not perfect and will likely fail when tokenizer_params become more complicate due to possible json key reordering.
@XuanYang-cn any idea? tracking this issue in https://github.com/milvus-io/pymilvus/issues/2299
=> fix: row based insert/upsert when there is Function in schema

pymilvus/client/constants.py, pymilvus/client/prepare.py
issue: https://github.com/milvus-io/milvus/issues/36986
=> fix: simplified the logic to check if the insert/request data matches the schema

examples/example_bulkinsert_csv.py, examples/example_bulkwriter.py, pymilvus/bulk_writer/buffer.py, pymilvus/bulk_writer/bulk_writer.py
https://github.com/milvus-io/pymilvus/issues/2276
=> fix: Fix the f16 and bf16 dump error & add all type test for csv & csv supports null

pymilvus/client/entity_helper.py, pymilvus/client/prepare.py
issue: https://github.com/milvus-io/milvus/issues/37022 and https://github.com/milvus-io/milvus/issues/37021
list of empty string is erroneously treated as sparse vector
adding a check to explicitly require that, if the input data will be seen as sparse vector, its data type, if not scipy format, should be list of list or list of dict.
=> fix: entity_is_sparse_matrix: each row should be dict or list

examples/hello_milvus.py
Fixed typo in comment of step 1 from "... buildin in ..." to "... is built-in to ..."
=> Fixed typo in comment of step 1

pymilvus/orm/schema.py
This PR updates several error messages for grammar and clarity. The changes include:
Corrected "data should be a list of list" to "The data should be a list of lists" for better readability.
Fixed grammar in "The data don't match with schema fields" to "The data doesn't match with schema fields."
Corrected field name mismatch message from "The name of field don't match" to "The name of the field doesn't match."
These improvements enhance the clarity and professionalism of error messages in the codebase.
=> Corrected grammar and consistency in error messages (#2289)

pymilvus/client/entity_helper.py, pymilvus/client/grpc_handler.py
Fix typo: change "UnSupported" to "Unsupported"
Fix grama error:
* _None entities, please provide valid entities_   to    _'entities' must be a list, please provide valid entity data._
* _None rows, please provide valid row data._    to    _'rows' must be a list, please provide valid row data._
=> Fix typo and correct grammar

examples/example_bulkinsert_withfunction.py, examples/hello_text_embedding.py, examples/milvus_client/text_embedding.py, pymilvus/client/types.py, pymilvus/exceptions.py, pymilvus/orm/schema.py
https://github.com/milvus-io/milvus/issues/35856
=> Add text embedding function

pymilvus/client/entity_helper.py
=> Correct grammar

pymilvus/client/check.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, tests/test_prepare.py
Also optinal variables default value should always be None.
And empty str is always invalid variable
See also: #2327
=> fix: cannot pass consistency level for delete

pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/role.py
=> enhance: format list privilege group result

examples/datatypes/bfloat16_example.py, examples/datatypes/float16_example.py
In the Python ecosystem, users may use basic libraries such as numpy,
Pandas, TensorFlow, PyTorch... to process float16/bfloat16 vectors.
However, users may have float32 vectors and are not clear about
how to handle float16/bfloat16 vectors in pymilvus.
Currently, pymilvus supports numpy array as embedding vector inputs.
However, numpy itself does not support bfloat16 type.
This PR demonstrates the way of converting float arrays in insert/search
API.
**insert (accept numpy array as input)**:
- float32 vector (owned by users) -> float16 vector (input param of insert API). numpy is enough, no more dependency.
- float32 vector (owned by users) -> bfloat16 vector (input param of insert API). Depends on `tf.bfloat16`. Pytorch can not convert `torch.bfloat16` to numpy array.
**search (the API …
=> enhance: update float16/bfloat16 examples

pymilvus/orm/utility.py
ListAliases SDK rpc call is `describeCollection`, which causes listing aliases successfully without granted.
issue: https://github.com/milvus-io/milvus/issues/38052
=> fix: fix list aliases rpc call

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/role.py
Since built-in privilege group level adjustment is not supported, remove the optional collection name from the grant/revoke v2 API. The empty db_name uses default db which follows the same rule as grant/revoke v1.
=> fix: remove grant/revoke v2 optional collection name

examples/orm/rbac.py, examples/rbac.py, pymilvus/milvus_client/milvus_client.py
=> enhance: rbac privilege group and grant v2 examples

pymilvus/client/__init__.py
=> fix pkg_resources api deprecated warning

pymilvus/client/grpc_handler.py, pymilvus/milvus_client/milvus_client.py
enhance createdatabase support properties
issue: https://github.com/milvus-io/pymilvus/issues/2447
=> enhance: [2.4]createdatabase support properties

examples/simple_async.py, pymilvus/__init__.py, pymilvus/client/async_grpc_handler.py, pymilvus/client/async_interceptor.py, pymilvus/milvus_client/__init__.py, pymilvus/milvus_client/async_milvus_client.py
- Support async delete, get, insert, query, search, hybrid_search, upsert, create_collection, drop_collection, describe_collection
- Support adding interceptor to aio channel
- Use `_async_channel.channel_ready()` in `_wait_for_channel_ready` instead of polling logic by `_async_channel.get_state()`
- Add `_async` parameter in `connections.py` to determine whether to establish a synchronous or asynchronous connection
- Update `__init__.py` to allow importing AsyncMilvusClient
- Add a simple code example for AsyncMilvusClient
Signed-off-by: Ruichen Bao <ruichen.bao@zju.edu.cn>
=> feat: [2.4] asyncio support

examples/simple_async.py, pymilvus/client/async_grpc_handler.py, pymilvus/client/async_interceptor.py, pymilvus/milvus_client/async_milvus_client.py
- add `authorization_interceptor` and `db_interceptor` to async channel
- fix call wrong function name when creating collection without schema
=> fix: [2.5] add `authorization_interceptor` and `db_interceptor` to async channel

pymilvus/client/async_grpc_handler.py, pymilvus/orm/connections.py
- Move check for channel ready and identifier interceptor setup before each query call instead of during the AsyncClient connection initialization
=> fix: remove async function in AsyncClient connection initialization

pymilvus/client/async_grpc_handler.py, pymilvus/orm/connections.py
- Add `wait_for_creating_index`, `wait_for_loading_collection` to ensure `create_index` and `load_collection` are fully completed
=> fix: [2.5] ensure `create_index` and `load_collection` are fully completed

examples/hybrid_search.py, examples/hybrid_search/hybrid_search.py, pymilvus/client/abstract.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/milvus_client/async_milvus_client.py
issue: https://github.com/milvus-io/milvus/issues/38616
=> fix: [2.4] Support hybrid search with expression template

pymilvus/milvus_client/milvus_client.py
pr: https://github.com/milvus-io/pymilvus/pull/2491
=> enhance: add use_database

examples/milvus_model/hello_model.py
Fixes a bug in `examples/milvus_model/hello_model.py` where indexing a sparse matrix with `x[0]` caused a `NotImplementedError`.
- Updated the sparse matrix indexing from `x[0]` to `x[:, [0]]` to use explicit 2D indexing, which is supported.
=> fix: Fix sparse slice bug in hello_model.py(#2414)

pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py
issue: milvus-io/milvus#38086
pr: #2396
cause RBAC require to check collection name, but ManualCompact rpc pass collection id in request, so grant ManualCompact api doesn't work.
This PR refine compact api impl to pass collection name in request.
=> fix: grant ManualCompact api doesn't work (#2396)

examples/resource_group.py, pymilvus/milvus_client/milvus_client.py
issue: milvus-io/milvus#38739
this PR enable those API in milvus client:
- create_resource_group
- update_resource_groups
- drop_resource_group
- describe_resource_group
- list_resource_groups
- transfer_replica
cause the resource group prefer to use declarative api, so the transfer_node API is deprecated in milvus client, it's recommand to use update_resource_group to manage node num in resource group.
=> enhance: Enable resource group api in milvus client

examples/resource_group.py, pymilvus/milvus_client/milvus_client.py
issue: milvus-io/milvus#38739
pr: #2513
this PR enable those API in milvus client:
- create_resource_group
- update_resource_groups
- drop_resource_group
- describe_resource_group
- list_resource_groups
- transfer_replica
cause the resource group prefer to use declarative api, so the transfer_node API is deprecated in milvus client, it's recommand to use update_resource_group to manage node num in resource group.
=> enhance: Enable resource group api in milvus client (#2513)

pymilvus/bulk_writer/bulk_import.py
The purpose of this PR is to align the parameter passing in the Python SDK with the RESTful API, and to add the missing "dbName" field.
see: https://milvus.io/api-reference/restful/v2.4.x/v2/Import%20(v2)/Create.md
> dbName
string
The name of the database that to which the collection belongs . Setting this to a non-existing database results in an error.
=> Add `db_name` parameter  at `bulk_import`

pymilvus/client/prepare.py, pymilvus/client/utils.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/collection.py
=> enhance: simplify the structure of search_params(#2507)(#2537)(#2540)

pymilvus/client/abstract.py, pymilvus/client/types.py, pymilvus/milvus_client/async_milvus_client.py, pymilvus/milvus_client/milvus_client.py, pyproject.toml
issue: https://github.com/milvus-io/milvus/issues/37899
=> enhance: support recalls for milvus_client

pymilvus/client/constants.py, pymilvus/client/prepare.py, pymilvus/orm/constants.py, pymilvus/orm/iterator.py
=> fix: iterator mismatch when alter alias and database(#2555)

pymilvus/client/utils.py
issue: #2576 
pr: https://github.com/milvus-io/pymilvus/pull/2577
Signed-off-by: Patrick Weizhi Xu <weizhi.xu@zilliz.com>
(cherry picked from commit 5050421ebb43867410d64ee364fb2cb78437bb54)
=> fix: [2.5] should not modify users search_param, copy instead

examples/partition.py, pymilvus/client/grpc_handler.py, pymilvus/client/types.py, pymilvus/milvus_client/milvus_client.py
=> enhance: enable describe_replica api in milvus client

pymilvus/client/types.py, tests/test_types.py
=> fix: Unify output of str(DataType) for different pythons

pymilvus/client/types.py, tests/test_types.py
=> fix: Unify output of str(DataType) for different pythons (#2635)

pymilvus/client/entity_helper.py
cherry pick https://github.com/milvus-io/pymilvus/pull/2309 and https://github.com/milvus-io/pymilvus/pull/2291.
support for empty sparse vector is added in 2.4.12 https://github.com/milvus-io/milvus/releases/tag/v2.4.12.
=> fix [2.4]: Allow empty sparse

pymilvus/bulk_writer/bulk_import.py
The purpose of this PR is to align the parameter passing in the Python SDK with the RESTful API, and to add the missing "dbName" field.
see:
https://milvus.io/api-reference/restful/v2.4.x/v2/Import%20(v2)/Create.md
> dbName
string
The name of the database that to which the collection belongs . Setting this to a non-existing database results in an error.
=> Add `db_name` parameter  at `bulk_import` (#2446)

pymilvus/orm/connections.py, tests/test_connections.py
Fix for this issue: https://github.com/milvus-io/pymilvus/issues/2670
Added a unit test for it as well.
=> Fix 2670: db_name overwritten by empty string

pymilvus/orm/connections.py, tests/test_connections.py
issue: https://github.com/milvus-io/pymilvus/issues/2670
pr: #2678
Added a unit test for it as well.
=> fix: [cp25]db_name overwritten by empty string (#2678)

pymilvus/bulk_writer/bulk_import.py
Issue: https://github.com/milvus-io/pymilvus/issues/2671
This PR addresses the above issue by adding optional CA certificate support to the below bulk import functions:
- **bulk_import**
- **get_import_progress**
- **list_import_jobs**
Now, users with TLS-mode milvus can use these functions in pymilvus, using their SSL-certificate.
=> Add Optional CA Certificate Support to Bulk Import Functions

pymilvus/orm/connections.py, tests/test_connections.py
Fix for [2727](https://github.com/milvus-io/pymilvus/issues/2727). Ensures that both passing a db_name as an explicit argument and as a path to the connection uri is used and not overwritten with an empty string. Added a couple of test cases.
=> fix: db_name will be overwritten by mistake

pymilvus/bulk_writer/bulk_import.py
Issue: https://github.com/milvus-io/pymilvus/issues/2671 This PR addresses the above issue by adding optional CA certificate support to the below bulk import functions:
- **bulk_import**
- **get_import_progress**
- **list_import_jobs**
Now, users with TLS-mode milvus can use these functions in pymilvus, using their SSL-certificate.
=> Add Optional CA Certificate Support to Bulk Import Functions (#2672)

examples/hybrid_search.py, examples/hybrid_search/hybrid_search.py, pymilvus/client/abstract.py, pymilvus/milvus_client/milvus_client.py
This PR handles the #2715 
It ensures that only one alias is used when calling connections.connect within the milvus client. This will allow users to create milvus connections to multiple milvus instances in the same context without worrying about collisions on aliases.
=> avoid collision on aliases in MilvusClient _create_connection

pymilvus/client/prepare.py
Related to milvus-io/milvus#39718
This PR fixes the issue that default value in input dict is not convert to result FieldSchema.default_value.
=> fix: [AddField] Fill default value in `get_field_schema`

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/client/interceptor.py, pymilvus/decorators.py
client-request-id is used to trace each API, and unique for each API. The previous code resets the channel for every API call to set it into global channel interceptor, which has great performance down and also will rewrite each other.
This PR adds client-request-id to per API metadata, and remove some of
the future calls.
See also: milvus-io#2761, milvus-io#2765
=> fix: Pass request-id in metadata per API

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/client/interceptor.py, pymilvus/decorators.py
client-request-id is used to trace each API, and unique for each API. The previous code resets the channel for every API call to set it into global channel interceptor, which has great performance down and also will rewrite each other.
This PR adds client-request-id to per API metadata, and remove some of the future calls.
See also: milvus-io#2761, milvus-io#2765, milvus-io#2766
=> fix: [cp25]Pass request-id in metadata per API (#2766)

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py
The default value should be decided in the server side
See also: #2781, milvus-io/milvus#41673
=> fix: remove default replica_number in load_collection

pymilvus/client/abstract.py
Cherry-pick from master
pr: #2777
Related to milvus-io/milvus#41639 milvus-io/milvus#41681 milvus-io/milvus#41688
=> fix: [2.5] Handle collection schema update timestamp (#2777)

pymilvus/client/async_grpc_handler.py, pymilvus/client/grpc_handler.py, pymilvus/client/prepare.py, pymilvus/orm/collection.py, pymilvus/orm/partition.py
The default value should be decided in the server side
See also: #2781, milvus-io/milvus#41673, #2782
=> fix: [cp25]remove default replica_number in load_collection (#2782)

pymilvus/milvus_client/milvus_client.py
This PR handles the #2715
It ensures that only one alias is used when calling connections.connect within the milvus client. This will allow users to create milvus connections to multiple milvus instances in the same context without worrying about collisions on aliases.
=> fix: [cp25]avoid collision on aliases in MilvusClient (#2716)

pymilvus/client/search_result.py, tests/test_search_result.py
`hasattr` calls against `Hit` instances fail with `KeyError`.
```python
>>> res = {
...   "my_id": 1,
...   "distance": 0.3
... }
>>> h = Hit(res, pk_name="my_id")
>>> hasattr(h, 'my_id')
True
>>> hasattr(h, '__pydantic_decorators__')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.12/site-packages/pymilvus/client/search_result.py", line 389, in __getattr__
return self.__getitem__(item)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymilvus/client/search_result.py", line 425, in __getitem__
return self.data["entity"][key]
~~~~~~~~~^^^^^^^^^^
KeyError: 'entity'
```
The current implementation of `Hit.__getattr__` raises `KeyError` when a requested key does not exist. But the only exception that is expected is …
=> Fixes hasattr checks against Hit for missing attributes

pymilvus/milvus_client/async_milvus_client.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/connections.py
To remove a one-time connection, we need to call
remove_connection instead of disconnect
=> fix: MilvusClient misusage of disconnect

pymilvus/client/prepare.py
fix: remove validation for collection_id in manual_compaction method
issue: https://github.com/milvus-io/pymilvus/issues/2839
=> fix: remove validation for collection_id in manual_compaction method

.gitignore, pymilvus/milvus_client/async_milvus_client.py, pymilvus/milvus_client/milvus_client.py, pymilvus/orm/connections.py, requirements.txt
1. enhance: reuse channel by default (#2873)
2. Bug fixes in async client (#2863) 3.build(deps): bump urllib3 from 1.26.19 to 2.5.0 (#2864)
=> enhance: Cherry pick multiple prs

pymilvus/client/prepare.py, pymilvus/exceptions.py, tests/test_prepare.py
=> fix: Refine partial upsert to preserve unspecified fields (#2955)

pymilvus/client/prepare.py, tests/test_prepare.py
This commit fixes a validation bug in the `_parse_upsert_row_request` function that incorrectly enforced field count consistency for partial updates.
=> fix: Correct validation logic for partial upsert requests

pymilvus/orm/connections.py, pyproject.toml, tests/test_milvus_lite.py
this PR is a possible implementation addressing this https://github.com/milvus-io/pymilvus/issues/2975
=> enhance: Make milvus-lite an optional dependency
