milvus-io/pymilvus

- TODO
- doc/en/API/milvus.client.rst
- doc/en/api.rst
- doc/en/conf.py
- doc/en/index.rst
- examples/example.py
- milvus/__init__.py
- milvus/client/Client.py
- setup.py
- tests/TestClient.py
> #1 fix add vector return value wrong bug

- CHANGELOG.md
- examples/example.py
- examples/simple_example.py
> #10 Update Examples

- milvus/__init__.py
- milvus/client/Client.py
- setup.py
> [ISSUE #15]Prepare version-0.1.5

- CHANGELOG.md
- examples/example.py
- milvus/client/Client.py
- tests/TestClient.py
> [ISSUE-#17] impl has_table

- CHANGELOG.md
- TODO
- milvus/__init__.py
- milvus/client/Client.py
- milvus/settings.py
- setup.py
- tests/TestClient.py
- tests/TestSearch.py
> [ISSUE #21] Range fully tested

- CHANGELOG.md
- milvus/__init__.py
- milvus/client/Client.py
- setup.py
> [ISSUE #23]

- CHANGELOG.md
- README.md
- TODO
- milvus/__init__.py
- milvus/client/Client.py
- milvus/settings.py
- setup.py
- tests/TestClient.py
> [ISSUE-#2]

- CHANGELOG.md
- milvus/__init__.py
- milvus/client/Client.py
- setup.py
- tests/TestClient.py
> [ISSUE-#41] fix prepare after prepare will raise exception bug

- examples/AdvancedExample.py
- milvus/client/Client.py
- milvus/client/Status.py
- milvus/settings.py
> [ISSUE-#45] completed

- examples/AdvancedExample.py
> [ISSUE - #47] Branch 0.3.1

- CHANGELOG.md
- examples/example.py
- milvus/__init__.py
- milvus/client/Abstract.py
- milvus/client/Client.py
- setup.py
- tests/TestClient.py
- tests/TestSearch.py
- tests/test_thread.py
> [ISSUE-#50-#51]fix a bug and add thread_safe

- CHANGELOG.md
- README.md
- TODO
- examples/example.py
- examples/simple_example.py
- milvus/__init__.py
- milvus/client/Abstract.py
- milvus/client/Client.py
- milvus/client/utils.py
- pytest.ini
- setup.py
- tests/TestClient.py
- tests/TestTimeout.py
> [ISSUE #59 #60] fixed MS-182, MS-185

- milvus/__init__.py
- milvus/client/Abstract.py
- milvus/client/Client.py
- setup.py
- tests/TestClient.py
> [ISSUE-#65] add new indextype

- CHANGELOG.md
- README.md
- examples/example.py
- milvus/__init__.py
- milvus/client/Client.py
- milvus/thrift/MilvusService-remote
- milvus/thrift/MilvusService.py
- milvus/thrift/ttypes.py
- setup.py
- tests/TestClient.py
- tests/TestSearch.py
- tests/test_serialize.py
> [ISSUE #69~#71]  all done

- CHANGELOG.md
- examples/AdvancedExample.py
- milvus/client/Abstract.py
- milvus/client/GrpcClient.py
- milvus/client/__init__.py
- milvus/client/utils.py
- setup.py
- tests/test_client.py
> Branch 0.4.0

- CHANGELOG.md
- README.md
- milvus/client/types.py
> Remove index type PQ

- CHANGELOG.md
- README.md
Signed-off-by: yhz <413554850@qq.com>
> fix incorrect demo in readme (fix #168)

- CHANGELOG.md
- examples/example.py
- examples/example_binary.py
- examples/example_partition.py
- examples/multiprocess_example.py
- milvus/client/grpc_handler.py
- tests/test_collection.py
Signed-off-by: yhz <413554850@qq.com>
* Fix #190
> Fix rpc return value error when error occur

- CHANGELOG.md
- README.md
>  Add sdk statistics badges (fix 220)

- milvus/client/http_handler.py
Unexpected nesting of Status i.e. `Status(Status(js["code"], js["message"]))`  is used in `http_handler.py`, just move all of them.
> Move unexpected nesting of Status

- README.md
update readme to milvus-0.11.0
> update readme to milvus-0.11.0

- CHANGELOG.md
- examples/example_delete.py
- milvus/client/stub.py
> Update api doc

- milvus/client/abstract.py
> fix result empty entity bug

- examples/example.py
> update example to 0.11.0

- README.md
> typo (#267)

- README.md
> typo (#267) (#268)

- examples/example.py
- examples/example_index.py
> fix example bug

- CHANGELOG.md
> start v0.3.1

- CHANGELOG.md
- README.md
> Fix parameter error for index_row_limit in readme (fix #284)

- .github/workflows/htmlpublish.yml
- .gitignore
- doc/source/res/query.md
> add alternative term query templates

- CHANGELOG.md
- README.md
> Add doc badge (fix #312)

- CHANGELOG.md
- README.md
> Fix incorrect comment about inserting data in README.md

- examples/example_async.py
> add example

- doc/source/res/query.md
Signed-off-by: godchen0212 <qingxiang.chen@zilliz.com>
fix the doc error
> fix the doc error

- examples/example.py
- examples/example_index.py
> fix typo in example

- .mergify/config.yml
- CHANGELOG.md
> Support auto merge PR after reviewed (fix #319)

- doc/source/install.rst
> grammar and build from source

- README.md
> fix API documentation link

- doc/source/res/Intro_to_Indexes.md
Signed-off-by: godchen0212 <qingxiang.chen@zilliz.com>
> change the index doc

- doc/source/res/Intro_to_Indexes.md
Signed-off-by: godchen0212 <qingxiang.chen@zilliz.com>
> fix index doc error

- requirements.txt
> fix requirements bug

- doc/source/res/query.md
> Update query chapter

- README.md
> Update readme (#340)

- CHANGELOG.md
- doc/source/contribute.rst
- doc/source/tutorial.rst
- examples/example.py
- examples/example_async.py
- milvus/client/__init__.py
- milvus/client/abs_client.py
- milvus/client/abstract.py
- milvus/client/grpc_handler.py
- milvus/client/prepare.py
- milvus/client/stub.py
- pylint.conf
- setup.py
- tests/factorys.py
- tests/test_bulk_insert.py
- tests/test_insert.py
> New method insert()

- doc/source/tutorial.rst
> fix tutorial doc but

- .github/scripts/server/milvus.yaml
- .github/scripts/server/server.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .mergify/config.yml
- CHANGELOG.md
- doc/source/contribute.rst
> Add Ci test in GitHub action

- milvus/client/abstract.py
fix a bug that func `Entity.__str__` not work as expected.
> fix class `Entity.__str__` func

- CHANGELOG.md
- doc/source/api.rst
- doc/source/res/Intro_to_Indexes.md
- doc/source/tutorial.rst
- examples/example.py
- examples/example_async.py
- examples/example_binary.py
- examples/example_index.py
> Example binary

- examples/example_index.py
> Add encoding utf-8

- doc/source/res/Intro_to_Indexes.md
> Fix index introduction typo

- CHANGELOG.md
- doc/source/res/Intro_to_Indexes.md
> Fix index doc wrong example and description (fix #368)

- doc/source/api.rst
Signed-off-by: PahudPlus <haimeng.cai@zilliz.com>
> [skip ci] Updated api.rst

- examples/example_index.py
> Add encoding utf-8 (#363)

- CHANGELOG.md
- milvus/client/stub.py
> Fix Wrong description in 'search_in_segment' method

- CHANGELOG.md
- milvus/client/prepare.py
- tests/test_insert.py
> Raise exception when inserted entities fields mismatch that at server endpoint

- CHANGELOG.md
- milvus/client/pool.py
- tests/test_mix.py
> Fix "too many values to unpack" if pool parameter is set to "QueuePool"

- .github/workflows/ci.yml
- .mergify/config.yml
> update github action behaviour

- .github/workflows/lint.yml
- CHANGELOG.md
- milvus/__init__.py
- milvus/client/grpc_client/grpc_gen/__init__.py
- milvus/client/grpc_client/grpc_results.py
- milvus/utils.py
- pylint.conf
> [ci] Optimize search result object to improve performance during loop

- .mergify/config.yml
> Modify mergify strategy

- milvus/client/grpc_client/grpc_handler.py
Address https://github.com/milvus-io/pymilvus/issues/400
> Fix typo in GrpcHandler

- doc/source/res/Intro_to_Indexes.md
- doc/source/tutorial.rst
- examples/example_binary.py
Signed-off-by: ireneontheway5 <qingying.hu@zilliz.com>
> [skip ci] Update links and docs.

- doc/source/res/query.md
> [skip ci] Fix dsl doc bug

- milvus/client/http_handler.py
- milvus/client/stub.py
> Add https support

- README.md
> Update milvus version contract table

- CHANGELOG.md
- milvus/client/__init__.py
- milvus/client/pool.py
> Prepare for 1.x

- README.md
> Update README version table

- README.md
> Update README version tables (#430)

- requirements.txt
> Update requirements for doc

- CHANGELOG.md
- README.md
- milvus/client/__init__.py
> Prepare Pymilvus v1.0.1

- docs/source/param.rst
- docs/source/param.rst.bak
- docs/source/res/Intro_to_Indexes.md
> Add index documentation

- docs/source/tutorial.rst
- requirements.txt
> Fix API documentation display fail

- .mergify/config.yml
- CHANGELOG.md
- conftest.py
- factorys.py
- milvus/client/check.py
- milvus/client/stub.py
- tests/test_insert.py
- tests/test_pool.py
> [ci] All test pass

- README.md
- docs/source/api.rst
- milvus/client/stub.py
- milvus/client/types.py
> Add IndexType and MetricType in documentation & Support cross-referencing

- README.md
> Update readme Compatibility version

- README.md
> Update readme Compatibility version (#471)

- setup.py
> Add author info in setup.py

- .github/workflows/package.yml
> Update GitHub Actions rules

- milvus/client/pool.py
> Update support versions

- milvus/client/http_handler.py
Fix: #496
See also: https://github.com/milvus-io/milvus/issues/5030
> Force using http/https scheme with http-handler

- .github/workflows/package.yml
- .gitignore
- pyproject.toml
- setup.py
> Add packaging for master branch

- setup.py
> Add mmh3 into install_requires

- setup.py
Pymilvus2.0 also contains this bug
See also: #517, #507, milvus-io/milvus#5377
> Control required version for grpcio and grpcio-tools

- milvus/client/prepare.py
> Copy search params to avoid changing the passed params

- milvus/client/grpc_handler.py
- milvus/client/prepare.py
- milvus/client/stub.py
> Add get method

- CHANGELOG.md
- README.md
> Prepare to release v1.1.1 (#529)

- README.md
> Change recommended version of pymilvus to 1.1.1

- milvus/client/abs_client.py
- milvus/client/check.py
- milvus/client/grpc_handler.py
- milvus/client/http_handler.py
- milvus/client/prepare.py
- milvus/client/stub.py
- tests/test_bulk_insert.py
- tests/test_insert.py
- tests/test_load_partitions.py
- tests/test_partition.py
- tests/test_search.py
> Change partition_tag to partition_name

- milvus/client/stub.py
> Update the docstring of get API

- milvus/client/grpc_handler.py
- milvus/client/prepare.py
- milvus/client/stub.py
> Fix retrieve request construct error

- milvus/client/abstract.py
> Convert dim type to int

- milvus/client/abstract.py
> Covert dim type to int

- pymilvus/client/prepare.py
> Fix type error of dim

- milvus/client/pool.py
- milvus/client/stub.py
> Pymilvus connection timeout

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
> Expr can be None of search

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
> Add Query API

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
> Fix bug for insert

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
> Ignore _id field when pymiluvs-orm call pymilvus

- pymilvus/client/prepare.py
> Fix bug for proto repeated field

- examples/query.py
- pymilvus/client/stub.py
> Add example for Query API

- examples/query.py
- pymilvus/client/grpc_handler.py
> Fix query grpc_handler

- examples/query.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/utils.py
> Add length method for field_data

- pymilvus/client/prepare.py
Signed-off-by: xiaocai2333 <cai.zhang@zilliz.com>
> Check params of search request

- pymilvus/client/stub.py
Signed-off-by: xiaocai2333 <cai.zhang@zilliz.com>
> Error message should be str not list

- pymilvus/client/stub.py
> Remove Get API

- pymilvus/client/stub.py
> Retry when rpc failure occurs

- pymilvus/client/stub.py
> Add comments for retry_on_rpc_failures

- grpc-proto/gen/milvus_pb2.py
- grpc-proto/gen/milvus_pb2_grpc.py
- grpc-proto/gen/schema_pb2.py
- grpc-proto/milvus.proto
- grpc-proto/schema.proto
- pymilvus/__init__.py
- pymilvus/client/abstract.py
- pymilvus/client/asynch.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
- pymilvus/grpc_gen/schema_pb2.py
> Redefine the auto_id and primary_key

- pymilvus/client/stub.py
See also [milvus repo issue #5857](https://github.com/milvus-io/milvus/issues/5857)
Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>
> Make wait for healthy timeout short

- examples/example.py
- grpc-proto/gen/milvus_pb2.py
- grpc-proto/gen/schema_pb2.py
- grpc-proto/milvus.proto
- grpc-proto/schema.proto
- pymilvus/client/abstract.py
- pymilvus/client/prepare.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/schema_pb2.py
> Search support target_entry

- pymilvus/client/prepare.py
Fix: [#5950](https://github.com/milvus-io/milvus/issues/5950)
> Check dimension when creating collection

- examples/example.py
- examples/example_index.py
- examples/query.py
- pymilvus/client/grpc_handler.py
> Fix query raise exception

- grpc-proto/gen/milvus_pb2.py
- grpc-proto/gen/milvus_pb2_grpc.py
- grpc-proto/milvus.proto
- pymilvus/client/asynch.py
- pymilvus/client/grpc_handler.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
> Update the logic of waiting for flushed

- pymilvus/client/grpc_handler.py
> Fix flush result

- examples/query.py
- pymilvus/client/abstract.py
> Complement entity class

- pymilvus/client/prepare.py
Solves: [#5950](https://github.com/milvus-io/milvus/issues/5950)
> Raise more clear exception when passed dimension is invalid

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
> Check if output_fields is list

- pymilvus/__init__.py
- pymilvus/client/asynch.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
> Rename SearchResultFuture and InsertFuture

- README.md
> Update PyMilvus version on README.md

- README.md
See also: https://github.com/milvus-io/milvus/issues/6021
> Fix recommended version of PyMilvus

- pymilvus/client/check.py
- pymilvus/client/stub.py
Solves: [#6170](https://github.com/milvus-io/milvus/issues/6170)
> Check limit

- pymilvus/client/asynch.py
Solves: [#6160](https://github.com/milvus-io/milvus/issues/6160)
> Call callback function when future.done() is called

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
Solves: [#6257](https://github.com/milvus-io/milvus/issues/6257)
> Check dimension of query vectors

- README.md
> Add slack channel link into readme

- pymilvus/client/asynch.py
> Optimize the workflow of future object

- pymilvus/client/stub.py
related issue: https://github.com/milvus-io/milvus/issues/6352
> Fix chaos testing failed

- pymilvus/client/abstract.py
> Fix float vector result handle

- pymilvus/client/abstract.py
Signed-off-by: kun yu <kun.yu@zilliz.com>
> Support binary_vector in target_entry

- pymilvus/client/asynch.py
> Fix async bug

- README.md
Signed-off-by: xiaocai2333 <cai.zhang@zilliz.com>
> Add rc2 for README

- pymilvus/client/asynch.py
> Fix search future

- pymilvus/client/check.py
- pymilvus/client/stub.py
issues: [#6538](https://github.com/milvus-io/milvus/issues/6538)
> Check if anns_field is legal

- pymilvus/client/check.py
- pymilvus/client/stub.py
issues: [#6541](https://github.com/milvus-io/milvus/issues/6541)
> Check if search data is legal

- pymilvus/client/check.py
- pymilvus/client/stub.py
issue: [#6592](https://github.com/milvus-io/milvus/issues/6592)
> Check partition_names and output_fields when search

- pymilvus/client/grpc_handler.py
See also:  https://github.com/milvus-io/milvus/issues/6374#issuecomment-889590321
> Fix load_collection timeout not working problem

- pymilvus/client/stub.py
> Fix bug for retry when rpc failure

- pymilvus/client/grpc_handler.py
- pymilvus/client/utils.py
> Support binary vector

- grpc-proto/gen/milvus_pb2.py
- grpc-proto/milvus.proto
- pymilvus/client/grpc_handler.py
- pymilvus/grpc_gen/milvus_pb2.py
Signed-off-by: xiaocai2333 <cai.zhang@zilliz.com>
> Enhance log when create index failed

- pymilvus/client/configs.py
- pymilvus/client/prepare.py
> Increase throughput of search

- pymilvus/client/grpc_handler.py
> Fixbug: use derived BaseException

- grpc-proto/gen/milvus_pb2.py
- grpc-proto/milvus.proto
- pymilvus/client/configs.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/grpc_gen/milvus_pb2.py
> Change the logic about waiting for loading collection/partitions

- README.md
> Add rc3 for README

- Makefile
> Comment not working target codecov

- pymilvus/__init__.py
> Fix cannot import DefaultConfig problem

- pymilvus/__init__.py
> Fix cannot import ExceptionsMessage error

- grpc-proto/gen/milvus_pb2.py
- grpc-proto/gen/milvus_pb2_grpc.py
- grpc-proto/milvus.proto
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
Resolves: #641 
See also: https://github.com/milvus-io/milvus/issues/7154
> Sync milvus.proto from milvus master branch

- setup.py
> Limit the grpc version in setup.py

- pymilvus/client/prepare.py
> Improper error returned by calc_distance

- pymilvus/client/prepare.py
https://github.com/milvus-io/milvus/issues/7046
> calc_distance missed partition name

- examples/example.py
- examples/old_style_example_distance.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/orm/pymilvus_orm/utility.py
https://github.com/milvus-io/milvus/issues/7038
> calc_distance error message bug

- pymilvus/client/prepare.py
https://github.com/milvus-io/milvus/issues/7217
> check calc_distance params

- docs/source/api/utility.rst
- pymilvus/__init__.py
- pymilvus/client/stub.py
- pymilvus/orm/pymilvus_orm/utility.py
- pymilvus/orm/tests/conftest.py
- pymilvus/orm/tests/mock_milvus.py
- pymilvus/orm/tests/test_collection.py
- pymilvus/orm/tests/test_connections.py
- pymilvus/orm/tests/test_index.py
- pymilvus/orm/tests/test_partition.py
- pymilvus/orm/tests/test_schema.py
- pymilvus/orm/tests/test_types.py
- pymilvus/orm/tests/test_utility.py
- pymilvus/orm/tests/utils.py
- Only expose `connections` and `Connections`
- Mend tests
- Add docs for drop_collections
Resolves: #652, #654
> Add util function to drop_collection

- .github/workflows/nightly_ci.yml
- ci/docker/milvus/docker-compose.yml
- ci/scripts/docker_image_find_tag.sh
Signed-off-by: quicksilver <zhifeng.zhang@zilliz.com>
Related issue: #657 
/cc @yanliang567
> Add Nightly CI

- pymilvus/client/stub.py
issue: https://github.com/milvus-io/milvus/issues/7306
> Remove retry logic when drop collection with deadline error

- README.md
- docs/source/conf.py
- docs/source/contribute.rst
- docs/source/install.rst
- docs/source/tutorial.rst
> Change newest version to rc5

- docs/source/api/utility.rst
> Add api reference for calc_distance

- README.md
Resolves: #684 
Signed-off-by: RahulMistri rahulmistri1997@gmail.com
> #Updated README.md with new documentation URL

- pymilvus/client/types.py
> Change value of standalone deployment key to keep same as server.

- Makefile
- pymilvus/client/stub.py
- pymilvus/orm/tests/conftest.py
- pymilvus/orm/tests/test_collection.py
- pymilvus/orm/tests/test_connections.py
- pymilvus/orm/tests/test_index.py
- pymilvus/orm/tests/test_partition.py
- pymilvus/orm/tests/test_types.py
- pymilvus/orm/tests/test_utility.py
Make orm tests runnable
Resolves: milvus-io/milvus#6889
> Raise error if connect after closing connection

- pymilvus/client/stub.py
> Make wait for healthy timeout controllable

- examples/collection.py
> An example of getting an existing collection

- pymilvus/client/stub.py
Resolves: milvus-io/milvus#7532
> Fix Milvus init error

- pymilvus/client/stub.py
Signed-off-by: jingkl <jingjing.jia@zilliz.com>
https://github.com/milvus-io/pymilvus/issues/696
> Remove check connect

- pymilvus/client/stub.py
> Raise NotImplementError when calling delete()

- README.md
- docs/source/conf.py
- docs/source/install.rst
> Update version in document

- pymilvus/orm/pymilvus_orm/collection.py
- pymilvus/orm/pymilvus_orm/exceptions.py
https://github.com/milvus-io/milvus/issues/7165
> Update SchemaNotReady exception msg when collection not exist

- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
- pymilvus/orm/pymilvus_orm/collection.py
Signed-off-by: Yunmei Li <yunmei.li@zilliz.com>
issue: #702
> support _async paramter for Load() interfance

- pymilvus/client/grpc_handler.py
> Check field name when create index

- CONTRIBUTING_CN.md
Signed-off-by: Yang Xuan <xuan.yang@zilliz.com>
> Add CONTRIBUTING_CN.md

- .github/workflows/nightly_ci.yml
Signed-off-by: Edward Zeng <jie.zeng@zilliz.com>
> Fix nightly ci github action

- examples/collection.py
- grpc-proto/common.proto
- grpc-proto/gen/common_pb2.py
- grpc-proto/gen/milvus_pb2.py
- grpc-proto/gen/milvus_pb2_grpc.py
- grpc-proto/milvus.proto
- pymilvus/client/abstract.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/grpc_gen/common_pb2.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
- pymilvus/orm/pymilvus_orm/collection.py
related: milvus-io/milvus#4812
> Implement alias api

- examples/collection.py
> Add example for alias

- pymilvus/client/stub.py
issue: https://github.com/milvus-io/milvus/issues/8353
> Change startup logic: wait enough time for server healthy

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
> Description for delete api

- examples/example.py
- examples/hello_milvus.py
- examples/partition.py
- pymilvus/client/abstract.py
- pymilvus/client/check.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
This PR add a “round_decimal” parameter for search function which helps search function to implement precision control(e.g. when round_decimal is 3, original output 3.134234 will be 3.134)
Resolves: #8573
Signed-off-by: elfisworking zymustb@126.com
Related PR in milvus: https://github.com/milvus-io/milvus/pull/8574
> For search function adding precision control

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
For old style search function which is used in old pymilvus version also adding a round decimal parameter to avoid  compatibility issues
Related issue: #8573
Signed-off-by: elfisworking <zymustb@126.com>
> For old style search function also adding a round decimal paramter

- grpc-proto/common.proto
- grpc-proto/gen/common_pb2.py
- grpc-proto/gen/milvus_pb2.py
- grpc-proto/milvus.proto
- pymilvus/grpc_gen/common_pb2.py
- pymilvus/grpc_gen/milvus_pb2.py
> Sync milvus.proto and common.proto with milvus repo

- pymilvus/client/stub.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
Fixes #775 
I have replaced all wrong instances of `raises` doc comment with the correct one. Do review it. :tada:
> Fixed all buggy format of `raises` doc comment

- pymilvus/client/check.py
- pymilvus/client/stub.py
issue: https://github.com/milvus-io/milvus/issues/10265
> Check the travel timestamp

- README.md
- docs/source/conf.py
- docs/source/install.rst
> Change docs for 2.0.0rc8

- .github/workflows/publish_dev_package.yml
- setup.py
Modify action to push dev packge to test.pypi
> Change package name for perf branch

- .github/workflows/publish_dev_package.yml
- README.md
> Trigger push perf package

- pymilvus/client/configs.py
> Do not divide search requests

- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
> Update the docstring of insert and delete method

- pymilvus/client/grpc_handler.py
> Enable delete function

- docs/source/contribute.rst
- docs/source/res/Intro_to_Indexes.md
- docs/source/tutorial.rst
Signed-off-by: czhen <zhen.chen@zilliz.com>
Refer to this issue: https://github.com/milvus-io/milvus/issues/11613
There're several broken links in `doc/**`.
> Fix broken link in doc

- pymilvus/orm/schema.py
output example:
```
The schema of hello_milvus: {
auto_id: False
description: hello_milvus is the simplest demo to introduce the APIs
fields: [{
name: pk
description: 
type: 5
is_primary: True
auto_id: False
}, {
name: random
description: 
type: 11
}, {
name: embeddings
description: 
type: 101
params: {'dim': 128}
}]
}
```
> Make scheme print nicer

- pymilvus/orm/utility.py
> Set params in load_balance as optional

- pymilvus/client/types.py
> Fix typos in types

- examples/example.py
Signed-off-by: Bennu <yunmei.li@zilliz.com>
issue: #769
> Rewrite the example.py

- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
- pymilvus/orm/collection.py
Signed-off-by: ThreadDao <yufen.zong@zilliz.com>
> Add method of waiting compaction completed

- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
issue: https://github.com/milvus-io/pymilvus/issues/813 https://github.com/milvus-io/milvus/issues/9618
Related: #814
> Set default consistency level to session

- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
Reverts milvus-io/pymilvus#821
> Revert "Set default consistency level to session"

- pymilvus/client/check.py
- pymilvus/client/stub.py
Signed-off-by: Cai.Zhang <cai.zhang@zilliz.com>
issue： https://github.com/milvus-io/milvus/issues/11985
> Check param for guarantee_timestamp

- examples/hello_milvus.py
- pymilvus/orm/collection.py
- pymilvus/orm/mutation.py
- pymilvus/orm/schema.py
> Add hellomilvus 2.0

- OWNERS
> Update the reviewers and approvers

- examples/hello_milvus.py
After deleting, the result is expected to be empty, thus line161 will raise an exception before this PR.
> Fix hello milvus exception

- docs/source/api/utility.rst
- pymilvus/orm/utility.py
/cc @czs007 
Signed-off-by: LocoRichard <lichen.wang@zilliz.com>
> [skip ci] Revise TS API Reference

- README.md
> Remove hacktoberfest banner

- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/proto/milvus.proto
> Add fieldID in DescribeSegmentResponse

- .github/workflows/pull_request.yml
- pymilvus/client/__init__.py
- tests/test_check.py
> Enable get git commit for a given version

- pymilvus/client/abstract.py
- pymilvus/client/constants.py
- pymilvus/client/exceptions.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/client/ts_utils.py
- pymilvus/client/types.py
- pymilvus/grpc_gen/common_pb2.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/proto/common.proto
- pymilvus/grpc_gen/proto/milvus.proto
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
- tests/test_ts_utils.py
- tests/test_types.py
issue: https://github.com/milvus-io/milvus/issues/9618
/kind enhancement
See also: https://github.com/milvus-io/milvus/pull/13766
> Support to configure the consistency level

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/client/ts_utils.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
> Support guarantee_timestamp & travel_timestamp for query

- examples/hello_milvus.ipynb
Resolves: #819 
Signed-off-by: DingQK <18210394728@163.com>
> Add hellomilvus in jupyter notebook

- CONTRIBUTING.md
Resolve: #763 
Signed-off-by: DingQK <18210394728@163.com>
> Add a English version of contributing_cn.md

- README.md
- docs/source/conf.py
- docs/source/install.rst
> Update version in documentation

- pymilvus/client/stub.py
> Remove retry after search deadline

- examples/hello_milvus.ipynb
- examples/hello_milvus.py
Signed-off-by: godchen <qingxiang.chen@zilliz.com>
> Fix hello milvus error

- pymilvus/client/ts_utils.py
> Downgrade ConsistencyLevel to Eventually when fetched zero guarantee_ts

- pymilvus/client/grpc_handler.py
- pymilvus/orm/types.py
> Fixbug: consistency_level not set

- pymilvus/client/grpc_handler.py
> Fix raising BaseException bug

- pymilvus/orm/utility.py
See also: milvus-io/milvus#15235
> Fix utility wait_for_loading method

- requirements.txt
- setup.py
> Limit the package dependency

- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
Signed-off-by: LocoRichard <lichen.wang@zilliz.com>
> [skip e2e] Revise API reference

- pymilvus/decorators.py
> Fix BaseExceptions in decorators

- pymilvus/decorators.py
> Add more detailed log before raising grpc.RpcError

- README.md
Fix documentation.
Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>
> Fix documentation url.

- docs/source/api/partition.rst
- pymilvus/orm/partition.py
Fixes: milvus-io/milvus#15420, milvus-io/milvus#15456
> Fix partition unable to delete bug

- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
> Support secure gRPC channel for AWS

- docs/source/faq.rst
Signed-off-by: LocoRichard <lichen.wang@zilliz.com>
> Update FAQ based on user's report

- pymilvus/client/grpc_handler.py
> Fix string consistency level not work

- pymilvus/client/blob.py
- pymilvus/client/prepare.py
> Speed up pack operation on float vector

- pymilvus/client/blob.py
> Speed up pack opertation on float vector

- docs/source/conf.py
> Change the doc version to 2.0.1

- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
> Support secure gRPC channel for AWS (#883)

- docs/source/faq.rst
Signed-off-by: LocoRichard <lichen.wang@zilliz.com>
> Update FAQ based on user's report (#886)

- pymilvus/client/grpc_handler.py
> Fix string consistency level not work (#887)

- pymilvus/client/blob.py
- pymilvus/client/prepare.py
> Speed up pack operation on float vector (#889)

- docs/source/conf.py
> Change the doc version to 2.0.1 (#893)

- OWNERS
> Update approvers and reviewers in OWNERS file

- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
> Fix create_partition doc string

- pymilvus/client/grpc_handler.py
- pymilvus/orm/collection.py
- pymilvus/orm/utility.py
Fixes: #milvus-io/milvus#15629
> Fix loading progress output

- examples/hello_milvus.ipynb
- examples/hello_milvus.py
- pymilvus/orm/prepare.py
> Add support for numpy.ndarray for vector field

- .github/workflows/publish_dev_package.yml
- setup.py
> Change pymilvus package name in perf branch

- pymilvus/client/configs.py
- pymilvus/orm/collection.py
Signed-off-by: Cai.Zhang <cai.zhang@zilliz.com>
> turn up rpc limit

- .github/workflows/publish_dev_package.yml
- .github/workflows/pull_request.yml
- requirements.txt
- setup.py
> Fix pymilvus unable to download on python3.8

- .github/workflows/publish_dev_package.yml
- setup.py
> Fix master branch unable to trigger pushlish package

- .github/mergify.yml
> Fix mergify rules for python3.8

- pymilvus/client/prepare.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/proto/milvus.proto
> Update proto in perf branch

- pymilvus/orm/collection.py
> Ignore check data schema

- examples/example_str.py
- examples/old_style_example_str.py
- pymilvus/client/configs.py
- pymilvus/client/entity_helper.py
- pymilvus/client/prepare.py
- pymilvus/orm/partition.py
- pymilvus/orm/prepare.py
- pymilvus/orm/schema.py
- pymilvus/orm/types.py
> Support to insert string

- examples/example_multiple_index.py
- pymilvus/client/configs.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/proto/milvus.proto
- pymilvus/orm/collection.py
- pymilvus/orm/index.py
> Support create index for scalar field

- docs/source/api/utility.rst
> Remove load balance from doc

- docs/source/api/utility.rst
> Remove load balance from doc (#928)

- pymilvus/orm/index.py
> Fix index_name in Index.drop()

- docs/source/conf.py
> Update doc version

- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
> Fix create_partition doc string (#899)

- OWNERS
> Update approvers and reviewers in OWNERS file (#901)

- .github/workflows/publish_dev_package.yml
- .github/workflows/pull_request.yml
- requirements.txt
- setup.py
> Fix pymilvus unable to download on python3.8 (#919)

- .github/mergify.yml
> Fix mergify rules for python3.8 (#921)

- README.md
> Fix readme bug (#900)

- pymilvus/client/grpc_handler.py
- pymilvus/orm/collection.py
- pymilvus/orm/utility.py
Fixes: #milvus-io/milvus#15629
> Fix loading progress output (#902)

- examples/hello_milvus.ipynb
- examples/hello_milvus.py
- pymilvus/orm/prepare.py
> Add support for numpy.ndarray for vector field (#904)

- docs/source/conf.py
> Update doc version (#938)

- setup.py
> Change scm version scheme to support 2.1.0.devx

- .github/mergify.yml
- .github/workflows/publish_dev_package.yml
- .github/workflows/pull_request.yml
- setup.py
> Make 2.0 branch function properly

- pymilvus/__init__.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/client/types.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
- pymilvus/grpc_gen/proto/milvus.proto
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
- tests/test_types.py
See also: milvus-io/milvus#16298
> Implement get_replicas in SDK

- pymilvus/__init__.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/client/types.py
- pymilvus/orm/utility.py
See also: https://wiki.lfaidata.foundation/display/MIL/MEP+24+--+Support+bulk+load
> Implement BulkLoad APIs

- examples/credential.py
- pymilvus/__init__.py
- pymilvus/client/check.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/interceptor.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
- pymilvus/grpc_gen/proto/milvus.proto
- pymilvus/orm/utility.py
/kind feature
See also: https://wiki.lfaidata.foundation/display/MIL/MEP+27+--+Support+Basic+Authentication
> Mep 27: Support Basic Authentication

- pymilvus/client/grpc_handler.py
> Fix loading progress check

- examples/multithreading_hello_milvus.py
> Add multithreading example

- pymilvus/orm/connections.py
> Add docstring for connect

- pymilvus/client/prepare.py
- pymilvus/client/types.py
> Fix get_bulk_load_state

- pymilvus/client/abstract.py
- pymilvus/client/grpc_handler.py
> Support string type in search/query result

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/grpc_gen/common_pb2.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/proto/common.proto
- pymilvus/grpc_gen/proto/milvus.proto
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
- pymilvus/orm/utility.py
/hold until https://github.com/milvus-io/milvus/pull/16470 is merged
> Update load_partitions and load_balance proto

- pymilvus/client/abstract.py
> Fix parse empty ids

- examples/example_str.py
- examples/old_style_example_str.py
- pymilvus/client/configs.py
- pymilvus/client/prepare.py
- pymilvus/orm/schema.py
> Fix insert string data from DataFrame

- pymilvus/client/grpc_handler.py
- pymilvus/client/types.py
- tests/test_types.py
> Alter group_nodes setter

- pymilvus/orm/connections.py
> Refactor connections

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/orm/utility.py
> Add more returns in loading_progress

- pymilvus/client/stub.py
> Fix replica_number param in stub

- pymilvus/client/prepare.py
issue: https://github.com/milvus-io/milvus/issues/16584
> Fix err msg when max_length_per_row is too large

- pymilvus/orm/schema.py
> Fix collection construct from dataframe

- pymilvus/client/abstract.py
> Fix schema mismatch when max_length_per_row is specified

- pymilvus/orm/connections.py
> Fix connection unable to connect to old alias

- pymilvus/orm/connections.py
This reverts commit fc8f07e6b3027d99b4059ef6d99dc9ac93667c4d.
> Revert "Fix connection unable to connect to old alias (#974)"

- examples/example_str.py
- pymilvus/client/configs.py
- pymilvus/orm/collection.py
> Add default max_length params when construct from df

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/client/types.py
- pymilvus/orm/utility.py
- Add `utility.list_bulk_load_tasks()`
- Remove `channel_names` in bulk_load API
See also: milvus-io/milvus#16690
> Add API for ListImportTasks

- pymilvus/orm/index.py
> Create Index with index_name

- pymilvus/orm/collection.py
fix issue: https://github.com/milvus-io/milvus/issues/16808
> Fix no default max_len params when auto_id=true

- pymilvus/client/grpc_handler.py
- pymilvus/orm/collection.py
- pymilvus/orm/index.py
- tests/test_collection.py
> Fix collection.Indexes with index_name

- pymilvus/client/grpc_handler.py
Signed-off-by: xiyichan <2863768433@qq.com>
> fix grpc support tls for self-signed certificate

- pymilvus/orm/collection.py
> Fix some docs

- Makefile
- pymilvus/orm/connections.py
- tests/test_collection.py
- tests/test_connections.py
> Add ut for add_connection

- pymilvus/client/grpc_handler.py
- pymilvus/orm/collection.py
fix issue: https://github.com/milvus-io/milvus/issues/16888
/kind bug
> Fix dup index_name params in describe_index when create_index

- OWNERS
> Add czs007 as reviewer and approver

- OWNERS
> Add czs007 as reviewer and approver (#995)

- pymilvus/orm/connections.py
- tests/test_connections.py
> Fix connect and add ut for connect

- pymilvus/client/configs.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
> Remove logic of splitting nq and delete unused code

- pymilvus/client/prepare.py
- pymilvus/client/types.py
- pymilvus/grpc_gen/common_pb2.py
- pymilvus/grpc_gen/milvus_pb2.py
> Add nq parameter to SearchRequest and update proto file

- .github/mergify.yml
> Enhance mergify on branch 2.0

- pymilvus/client/grpc_handler.py
- pymilvus/client/ts_utils.py
- tests/test_ts_utils.py
Signed-off-by: longjiquan <jiquan.long@zilliz.com>
> Maintain session consistency according to collection name

- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
- pymilvus/decorators.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
- pymilvus/orm/utility.py
- Make sure ever timeout parameter is the last position param
- Remove check_has_collection
- Enable timeout to control retry times
See also: milvus-io/milvus#16835
> Enable timeout to control retry times

- pymilvus/client/stub.py
- pymilvus/decorators.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
- pymilvus/orm/utility.py
- Get rid of dagerous args slice
- Make sure all the API passes timout by kwargs form
`search(..., timeout=timeout)`
Fixes: #1015
> Fix nightly index out of range

- pymilvus/__init__.py
- pymilvus/decorators.py
- pymilvus/exceptions.py
- tests/conftest.py
- tests/test_grpc_handler.py
See also: milvus-io/milvus#16835
> Add Milvus Unavaliable Exception

- pymilvus/grpc_gen/milvus_pb2.py
Signed-off-by: yah01 <yang.cen@zilliz.com>
> Add nodeIds for QuerySegmentInfo

- pymilvus/client/constants.py
- pymilvus/client/ts_utils.py
- tests/test_ts_utils.py
> Set guarantee_timestamp to 2 in case of Bounded consistency level

- pymilvus/__init__.py
- pymilvus/client/exceptions.py
- pymilvus/client/grpc_handler.py
- pymilvus/decorators.py
- pymilvus/orm/exceptions.py
> Add Milvus Unavaliable Exception (#1017)

- docs/source/conf.py
- requirements.txt
> Enable sphinxcontrib-napoleon in sphnix docs

- examples/example_str.py
- examples/old_style_example_str.py
- pymilvus/client/configs.py
- pymilvus/orm/constants.py
fix issue: https://github.com/milvus-io/milvus/issues/17014
> Alter varChar type params's name to max_length

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/orm/utility.py
Signed-off-by: Cai.Zhang <cai.zhang@zilliz.com>
> Supprot index_name for get_index_state

- pymilvus/client/grpc_handler.py
- pymilvus/client/types.py
- pymilvus/grpc_gen/common_pb2.py
- pymilvus/grpc_gen/milvus_pb2.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
in both get_bulk_load_state() and list_bulk_load_tasks()
Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>
> Support DataQueryable and DataIndex states

- pymilvus/orm/collection.py
- pymilvus/orm/utility.py
Signed-off-by: 赵星 <zhaoxing@zhaoxings-MacBook-Pro.local>
https://github.com/milvus-io/pymilvus/issues/1027
> add listaliases and Collection.aliases (#1027)

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/types.py
- pymilvus/exceptions.py
- pymilvus/orm/collection.py
- pymilvus/orm/constants.py
- pymilvus/orm/schema.py
- tests/test_grpc_handler.py
- tests/test_prepare.py
- tests/test_schema.py
> Add ut for prepare.create_collection_request

- pymilvus/client/grpc_handler.py
- pymilvus/client/types.py
- pymilvus/exceptions.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
> Reduce calls to describe_collection to speed up

- examples/example_bulkload.py
- pymilvus/client/types.py
Signed-off-by: groot <yihua.mo@zilliz.com>
> Numpy example for bulkload

- .github/workflows/nightly_ci.yml
> Test L1 cases in nightly

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/orm/utility.py
Remove field_name in
- wait_for_create_index
- index_building_progress
- wait_for_index_building_complete
- get_index_state
- get_index_building_progress
> Enable index_name and disable field_name

- pymilvus/client/grpc_handler.py
- pymilvus/decorators.py
- tests/pytest.ini
- tests/test_grpc_handler.py
link: https://github.com/milvus-io/milvus/issues/17606
> Use warning instead of error to print log during retry

- pymilvus/client/grpc_handler.py
- pymilvus/decorators.py
- tests/test_grpc_handler.py
> Fix the wrong function name in the error_handler

- pymilvus/decorators.py
- tests/test_decorators.py
- tests/test_grpc_handler.py
> Add more ut for decorators

- .github/workflows/nightly_ci.yml
This PR also enables manually run night ci for debug.
Fixes: #1046
> Fix nightly failure

- pymilvus/client/check.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
- pymilvus/orm/connections.py
- tests/test_check.py
- tests/test_connections.py
- tests/test_grpc_handler.py
> Enable to connect with uri and address

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
This PR:
- Add static checks for partition_names
- Add dynamic checks for partitions_names
See also: #677, milvus-io/milvus#16753
> Fix loading_progress problems with partitions

- pymilvus/orm/connections.py
- tests/test_connections.py
> Fix exception error code 0

- pymilvus/client/grpc_handler.py
- pymilvus/client/stub.py
See also: milvus-io/milvus#17951
> Fix connect with Milvus

- pymilvus/client/abstract.py
- pymilvus/orm/mutation.py
Signed-off-by: longjiquan <jiquan.long@zilliz.com>
issue: https://github.com/milvus-io/milvus/issues/17697
> Add err_count & succ_count to mutation result

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
> Fix show partitions unable to show all

- pymilvus/client/abstract.py
- pymilvus/orm/mutation.py
Signed-off-by: longjiquan <jiquan.long@zilliz.com>
issue: https://github.com/milvus-io/milvus/issues/18091, https://github.com/milvus-io/milvus/issues/17697
> Fix mutation result

- requirements.txt
- setup.py
Signed-off-by: yun.zhang <yun.zhang@zilliz.com>
> Upgrade grpc version to 1.47.0

- examples/hello_milvus.ipynb
- examples/hello_milvus.py
resolves: #1069
Signed-off-by: Ziyu Wang <wzyubill1104@gmail.com>
> Fix metric type in hello milvus

- pymilvus/decorators.py
- tests/test_decorators.py
Signed-off-by: yun.zhang <yun.zhang@zilliz.com>
> Descreasing initial back off time

- examples/hello_milvus.ipynb
- examples/hello_milvus.py
> Add VarChar in hello milvus

- README.md
- docs/source/conf.py
> Prepare to release pymilvus2.1.0

- pymilvus/__init__.py
- pymilvus/decorators.py
- pymilvus/exceptions.py
- tests/test_decorators.py
- tests/test_grpc_handler.py
Signed-off-by: zhuwenxing <wenxing.zhu@zilliz.com>
resolves: https://github.com/milvus-io/pymilvus/issues/1074
> Fix typo `Unavaliable`

- .github/workflows/publish_dev_package.yml
> Enable branch 2.1 to publish dev packge

- .github/mergify.yml
> Fix mergify rules

- .github/workflows/pull_request.yml
> Fix ut action for branch 2.1

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/orm/collection.py
- tests/test_grpc_handler.py
See also: milvus-io/milvus#18455
> Remove usage of HasCollection

- examples/hello_milvus.py
- pymilvus/orm/collection.py
- pymilvus/orm/partition.py
See also: milvus-io/milvus#18459
> Remove flush in num_entities

- examples/user.py
- pymilvus/__init__.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/orm/utility.py
> Rename Credential api names

- pymilvus/client/abstract.py
- pymilvus/client/grpc_handler.py
Related to #1097 
Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>
> Enable DataType.BOOL

- pymilvus/orm/utility.py
> Fix the `list_roles` function in the `utility.py` file

- examples/role_and_privilege.py
> Update `rbac` function usage example file

- README.md
- docs/source/conf.py
> Change doc versions to 2.1.1

- pymilvus/client/utils.py
> Delete useless index params

- .github/mergify.yml
> Fix mergify regex

- pymilvus/orm/role.py
> Fix the `is_exist` function in the `Role` object

- pymilvus/orm/role.py
> Improve the result of `get_users` function in the `Role` object

- setup.py
> Add upbound for grpcio in-compatibility 1.49.0.rc1

- pymilvus/decorators.py
- tests/test_decorators.py
> Support retry when requests are rejected due to rate limit

- pymilvus/__init__.py
- pymilvus/client/grpc_handler.py
- pymilvus/decorators.py
> add client log level and client quest id for rpc calls

- pymilvus/client/grpc_handler.py
See also #1117 
/kind bug
Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>
> Raise exception if wait collection loaded timeout

- pymilvus/client/prepare.py
- tests/test_prepare.py
> Enable offset in search_params

- .github/workflows/check_milvus_proto.yml
- setup.py
> Enable proto check at branch 2.1

- pymilvus/client/entity_helper.py
https://github.com/milvus-io/milvus/issues/18985
> Fix binary vector insert performance issue

- pymilvus/client/prepare.py
- pymilvus/exceptions.py
- pymilvus/orm/collection.py
- pymilvus/orm/schema.py
- tests/test_prepare.py
> Refine CreateCollectionRequest

- pymilvus/client/check.py
- pymilvus/client/grpc_handler.py
- tests/test_check.py
> Fix error message with type error

- pymilvus/client/grpc_handler.py
See also: milvus-io/milvus#17115
> Add type check for secure in connect

- pymilvus/client/abstract.py
- pymilvus/client/grpc_handler.py
Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>
> Enable DataType.BOOL (#1098)

- pymilvus/decorators.py
- tests/test_decorators.py
> Catch rate limit and force deny error

- pymilvus/__init__.py
- pymilvus/client/grpc_handler.py
- pymilvus/orm/types.py
- pymilvus/settings.py
- tests/test_index.py
- tests/test_partition.py
- tests/test_schema.py
> Remove not in use LOGGER

- pymilvus/client/grpc_handler.py
Signed-off-by: Enwei Jiao <enwei.jiao@zilliz.com>
issue:  https://github.com/milvus-io/pymilvus/issues/1152
> fix invalid index type is not str

- pymilvus/client/utils.py
> Add autoindex type

- pymilvus/client/check.py
- pymilvus/client/utils.py
> Fix bug: add autoindex type in check

- pymilvus/orm/collection.py
- pymilvus/orm/index.py
- pymilvus/orm/partition.py
> Fix partial orm api missing kwargs

- pymilvus/__init__.py
- pymilvus/client/abstract.py
- pymilvus/client/asynch.py
- pymilvus/client/check.py
- pymilvus/client/entity_helper.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/singleton_utils.py
- pymilvus/client/stub.py
- pymilvus/client/types.py
- pymilvus/client/utils.py
- pymilvus/decorators.py
- pymilvus/exceptions.py
- pymilvus/orm/collection.py
- pymilvus/orm/connections.py
- pymilvus/orm/constants.py
- pymilvus/orm/index.py
- pymilvus/orm/partition.py
- pymilvus/orm/prepare.py
- pymilvus/orm/schema.py
- pymilvus/orm/utility.py
- pymilvus/settings.py
- tests/test_connections.py
Signed-off-by: longjiquan <jiquan.long@zilliz.com>
> Revert "Refine Exception handling"

- pymilvus/client/grpc_handler.py
https://github.com/milvus-io/pymilvus/issues/1175
I don't see this functionality covered by tests. I can add a bunch of tests but I need more info about test strategy.
> fix broken _async in delete()

- pymilvus/decorators.py
> Remove print when rate limit

- .gitmodules
- examples/example_udf.py
- examples/hello_milvus_udf.py
- pymilvus/__init__.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/grpc_gen/milvus_pb2_grpc.py
- pymilvus/orm/utility.py
1. create function
2. drop function
3. using new milvus_proto from my [milvus_proto](https://github.com/milvus-ospp-2022-wasm-udf/milvus-proto)
Signed-off-by: Ziyu Wang <15871035978@163.com>
> Add function storage interface

- pymilvus/client/grpc_handler.py
issue: [19396](https://github.com/milvus-io/milvus/issues/19396)
> Support create flat index

- examples/example_bulkload.py
- pymilvus/__init__.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/client/types.py
- pymilvus/orm/collection.py
- pymilvus/orm/utility.py
> Rename bulkload to bulkinsert

- pymilvus/orm/partition.py
> Fix a typo

- examples/hello_milvus.py
> Add example for pagination

- pymilvus/__init__.py
- pymilvus/client/abstract.py
- pymilvus/client/asynch.py
- pymilvus/client/check.py
- pymilvus/client/entity_helper.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/singleton_utils.py
- pymilvus/client/stub.py
- pymilvus/client/types.py
- pymilvus/client/utils.py
- pymilvus/decorators.py
- pymilvus/exceptions.py
- pymilvus/orm/collection.py
- pymilvus/orm/connections.py
- pymilvus/orm/constants.py
- pymilvus/orm/index.py
- pymilvus/orm/partition.py
- pymilvus/orm/prepare.py
- pymilvus/orm/schema.py
- pymilvus/settings.py
- tests/test_connections.py
This reverts commit ba1ba5d635cf479faa1b7773004d8056e58b8319.
> Refine Exception handling (#1173)

- pymilvus/orm/collection.py
- tests/test_collection.py
> Dropping index must happen without collection being loaded

- pymilvus/client/grpc_handler.py
see also #1191
Add more information when wait timeout
Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>
> Add more information when wait timeout

- pymilvus/orm/collection.py
> Only send drop collection request to milvus server

- pymilvus/client/grpc_handler.py
> Remove flush in create index

- examples/example_bulkload.py
- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
- pymilvus/client/stub.py
- pymilvus/orm/utility.py
> Remove is_row_based flag of bulk_insert()

- pymilvus/client/grpc_handler.py
- pymilvus/client/prepare.py
> Do not set default index name for creating index

- pymilvus/orm/collection.py
> Don't set default index name when drop index 
